//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MecTelAirtimeWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MecTelAirtimeWCF.IMecTelAirtime")]
    public interface IMecTelAirtime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecTelAirtime/GetData", ReplyAction="http://tempuri.org/IMecTelAirtime/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecTelAirtime/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMecTelAirtime/GetDataUsingDataContractResponse")]
        MecTelAirtimeWCF.CompositeType GetDataUsingDataContract(MecTelAirtimeWCF.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMecTelAirtime/BalanceUpdatewithReferenceCode", ReplyAction="http://tempuri.org/IMecTelAirtime/BalanceUpdatewithReferenceCodeResponse")]
        bool BalanceUpdatewithReferenceCode(out string errMsg, string teleNo, decimal amount, string balanceUpdateReferenceCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMecTelAirtimeChannel : MecTelAirtimeWCF.IMecTelAirtime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MecTelAirtimeClient : System.ServiceModel.ClientBase<MecTelAirtimeWCF.IMecTelAirtime>, MecTelAirtimeWCF.IMecTelAirtime {
        
        public MecTelAirtimeClient() {
        }
        
        public MecTelAirtimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MecTelAirtimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MecTelAirtimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MecTelAirtimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public MecTelAirtimeWCF.CompositeType GetDataUsingDataContract(MecTelAirtimeWCF.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public bool BalanceUpdatewithReferenceCode(out string errMsg, string teleNo, decimal amount, string balanceUpdateReferenceCode) {
            return base.Channel.BalanceUpdatewithReferenceCode(out errMsg, teleNo, amount, balanceUpdateReferenceCode);
        }
    }
}
