//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahaAwbaWCF {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MahaAwbaWCF.RouteWebServiceSoap")]
    public interface RouteWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobileLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode MobileLogin(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetServerLog(string branchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRepaymentInquiryInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRepaymentInquiryInfo(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRepaymentComfirmation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRepaymentComfirmation(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDisbursement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddDisbursement(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSurveyVillageForMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddSurveyVillageForMobile(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTownSurveyForMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddTownSurveyForMobile(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSMESurveyForMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddSMESurveyForMobile(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCustRegVendorForMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddCustRegVendorForMobile(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCustRegFarmerForMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddCustRegFarmerForMobile(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLoanApplicationFarmerForMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddLoanApplicationFarmerForMobile(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddLoanApplicationVendorForMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddLoanApplicationVendorForMobile(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifiedSurveySME", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVerifiedSurveySME(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUserDataByBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllUserDataByBranch(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMasterData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetMasterData(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLoanProductType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllLoanProductType(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDisbursementData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllDisbursementData(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLoanProductTypeItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllLoanProductTypeItem(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMicroLoan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllMicroLoan(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMicroTerm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetAllMicroTerm(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifiedSurveyTown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVerifiedSurveyTown(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifiedSurveyFarmVillage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVerifiedSurveyFarmVillage(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifiedCustRegFarmer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVerifiedCustRegFarmer(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifiedCustRegVendor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVerifiedCustRegVendor(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifiedLoanAppFarmer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVerifiedLoanAppFarmer(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVerifiedLoanAppVendor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetVerifiedLoanAppVendor(string xmldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDataForFingerPrint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserDataForFingerPrint(MahaAwbaWCF.RequestParameter para);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DesktopLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DesktopLogin(MahaAwbaWCF.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifiedCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool VerifiedCustomer(MahaAwbaWCF.UserAccount user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerDataForFingerPrint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCustomerDataForFingerPrint(MahaAwbaWCF.RequestParameter para);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUserForDesktop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddUserForDesktop(MahaAwbaWCF.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCustomerForDesktop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddCustomerForDesktop(MahaAwbaWCF.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomerForDesktop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateCustomerForDesktop(MahaAwbaWCF.Customer customer);
        
        // CODEGEN: Parameter 'fingerPrint' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerVerifiedLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MahaAwbaWCF.CustomerVerifiedLoginResponse CustomerVerifiedLogin(MahaAwbaWCF.CustomerVerifiedLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddUser(MahaAwbaWCF.User para);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddtestData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AddtestData(string name, string serverName, string ipAddress, string userId, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string branchCodeField;
        
        private int createdUserIdField;
        
        private string versionField;
        
        private string timeStampField;
        
        private string messageIDField;
        
        private string customerIDField;
        
        private string slipNoField;
        
        private decimal amountField;
        
        private decimal interestAmountField;
        
        private decimal penalFeesAmountField;
        
        private string hashValueField;
        
        private string resCodeField;
        
        private decimal dueDateField;
        
        private string loanTypeField;
        
        private string descField;
        
        private decimal loanAmountField;
        
        private decimal savingAmountField;
        
        private string contractNoField;
        
        private string loanNoField;
        
        private string receiptNoField;
        
        private int userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CreatedUserId {
            get {
                return this.createdUserIdField;
            }
            set {
                this.createdUserIdField = value;
                this.RaisePropertyChanged("CreatedUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SlipNo {
            get {
                return this.slipNoField;
            }
            set {
                this.slipNoField = value;
                this.RaisePropertyChanged("SlipNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal InterestAmount {
            get {
                return this.interestAmountField;
            }
            set {
                this.interestAmountField = value;
                this.RaisePropertyChanged("InterestAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal PenalFeesAmount {
            get {
                return this.penalFeesAmountField;
            }
            set {
                this.penalFeesAmountField = value;
                this.RaisePropertyChanged("PenalFeesAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string HashValue {
            get {
                return this.hashValueField;
            }
            set {
                this.hashValueField = value;
                this.RaisePropertyChanged("HashValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ResCode {
            get {
                return this.resCodeField;
            }
            set {
                this.resCodeField = value;
                this.RaisePropertyChanged("ResCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("DueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string LoanType {
            get {
                return this.loanTypeField;
            }
            set {
                this.loanTypeField = value;
                this.RaisePropertyChanged("LoanType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("Desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal LoanAmount {
            get {
                return this.loanAmountField;
            }
            set {
                this.loanAmountField = value;
                this.RaisePropertyChanged("LoanAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal SavingAmount {
            get {
                return this.savingAmountField;
            }
            set {
                this.savingAmountField = value;
                this.RaisePropertyChanged("SavingAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ContractNo {
            get {
                return this.contractNoField;
            }
            set {
                this.contractNoField = value;
                this.RaisePropertyChanged("ContractNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LoanNo {
            get {
                return this.loanNoField;
            }
            set {
                this.loanNoField = value;
                this.RaisePropertyChanged("LoanNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ReceiptNo {
            get {
                return this.receiptNoField;
            }
            set {
                this.receiptNoField = value;
                this.RaisePropertyChanged("ReceiptNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rdgIDField;
        
        private string custIdField;
        
        private byte[] fingerPrintField;
        
        private string branchCodeField;
        
        private bool activeField;
        
        private TimeSpan tsField;
        
        private System.DateTime createdDateField;
        
        private int createdUserIdField;
        
        private System.DateTime updatedDateField;
        
        private int updatedUserIdField;
        
        private string nameField;
        
        private string nameInMyanmarField;
        
        private bool isAwbaCustomerField;
        
        private System.DateTime dOBField;
        
        private string genderField;
        
        private int ageField;
        
        private bool hasSmartPhoneField;
        
        private string phoneNoField;
        
        private int noOfFamilyMemField;
        
        private double foodLivingField;
        
        private int noOfStudentField;
        
        private double schoolYearCostField;
        
        private double totalAcresField;
        
        private string nRCField;
        
        private string addressField;
        
        private string fatherNameField;
        
        private string emailField;
        
        private string remarkField;
        
        private string initialCodeField;
        
        private string nameOnlyField;
        
        private System.DateTime dATE_TIMEField;
        
        private string occupationCodeField;
        
        private string stateCodeField;
        
        private string cityCodeField;
        
        private string townshipCodeField;
        
        private string villageCodeField;
        
        private int noOfEmployesField;
        
        private int noOfCustomerField;
        
        private string memberLevelCodeField;
        
        private System.DateTime firstLoanDateField;
        
        private int noOfLoansField;
        
        private string hubCodeField;
        
        private double highestDepositField;
        
        private double currentDepositField;
        
        private double totalAmtLoansField;
        
        private double currentLoanOutstandingField;
        
        private double onTimePaymentField;
        
        private System.DateTime closeDateField;
        
        private double overPayField;
        
        private double underPayField;
        
        private string sMETypeCodeField;
        
        private string sMEGroupCodeField;
        
        private string storeLocationCodeField;
        
        private string vendorTypeCodeField;
        
        private string tradeTypeCodeField;
        
        private string verifyStatusBranchField;
        
        private string verifyStatusHubField;
        
        private int vSBranchUserIdField;
        
        private int vSHubUserIdField;
        
        private System.DateTime vSBranchDateField;
        
        private System.DateTime vSHubDateField;
        
        private byte[] facePicField;
        
        private byte[] signatureField;
        
        private byte[] nRCBackPicField;
        
        private byte[] nRCFrontPicField;
        
        private byte[] landTitleDeedPicField;
        
        private byte[] houseHoldRegisPicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RdgID {
            get {
                return this.rdgIDField;
            }
            set {
                this.rdgIDField = value;
                this.RaisePropertyChanged("RdgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustId {
            get {
                return this.custIdField;
            }
            set {
                this.custIdField = value;
                this.RaisePropertyChanged("CustId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] FingerPrint {
            get {
                return this.fingerPrintField;
            }
            set {
                this.fingerPrintField = value;
                this.RaisePropertyChanged("FingerPrint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TimeSpan TS {
            get {
                return this.tsField;
            }
            set {
                this.tsField = value;
                this.RaisePropertyChanged("TS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CreatedUserId {
            get {
                return this.createdUserIdField;
            }
            set {
                this.createdUserIdField = value;
                this.RaisePropertyChanged("CreatedUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime UpdatedDate {
            get {
                return this.updatedDateField;
            }
            set {
                this.updatedDateField = value;
                this.RaisePropertyChanged("UpdatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int UpdatedUserId {
            get {
                return this.updatedUserIdField;
            }
            set {
                this.updatedUserIdField = value;
                this.RaisePropertyChanged("UpdatedUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NameInMyanmar {
            get {
                return this.nameInMyanmarField;
            }
            set {
                this.nameInMyanmarField = value;
                this.RaisePropertyChanged("NameInMyanmar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsAwbaCustomer {
            get {
                return this.isAwbaCustomerField;
            }
            set {
                this.isAwbaCustomerField = value;
                this.RaisePropertyChanged("IsAwbaCustomer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool HasSmartPhone {
            get {
                return this.hasSmartPhoneField;
            }
            set {
                this.hasSmartPhoneField = value;
                this.RaisePropertyChanged("HasSmartPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int NoOfFamilyMem {
            get {
                return this.noOfFamilyMemField;
            }
            set {
                this.noOfFamilyMemField = value;
                this.RaisePropertyChanged("NoOfFamilyMem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double FoodLiving {
            get {
                return this.foodLivingField;
            }
            set {
                this.foodLivingField = value;
                this.RaisePropertyChanged("FoodLiving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int NoOfStudent {
            get {
                return this.noOfStudentField;
            }
            set {
                this.noOfStudentField = value;
                this.RaisePropertyChanged("NoOfStudent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public double SchoolYearCost {
            get {
                return this.schoolYearCostField;
            }
            set {
                this.schoolYearCostField = value;
                this.RaisePropertyChanged("SchoolYearCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public double TotalAcres {
            get {
                return this.totalAcresField;
            }
            set {
                this.totalAcresField = value;
                this.RaisePropertyChanged("TotalAcres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string NRC {
            get {
                return this.nRCField;
            }
            set {
                this.nRCField = value;
                this.RaisePropertyChanged("NRC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string FatherName {
            get {
                return this.fatherNameField;
            }
            set {
                this.fatherNameField = value;
                this.RaisePropertyChanged("FatherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string InitialCode {
            get {
                return this.initialCodeField;
            }
            set {
                this.initialCodeField = value;
                this.RaisePropertyChanged("InitialCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string NameOnly {
            get {
                return this.nameOnlyField;
            }
            set {
                this.nameOnlyField = value;
                this.RaisePropertyChanged("NameOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public System.DateTime DATE_TIME {
            get {
                return this.dATE_TIMEField;
            }
            set {
                this.dATE_TIMEField = value;
                this.RaisePropertyChanged("DATE_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string OccupationCode {
            get {
                return this.occupationCodeField;
            }
            set {
                this.occupationCodeField = value;
                this.RaisePropertyChanged("OccupationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("CityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string TownshipCode {
            get {
                return this.townshipCodeField;
            }
            set {
                this.townshipCodeField = value;
                this.RaisePropertyChanged("TownshipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string VillageCode {
            get {
                return this.villageCodeField;
            }
            set {
                this.villageCodeField = value;
                this.RaisePropertyChanged("VillageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int NoOfEmployes {
            get {
                return this.noOfEmployesField;
            }
            set {
                this.noOfEmployesField = value;
                this.RaisePropertyChanged("NoOfEmployes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int NoOfCustomer {
            get {
                return this.noOfCustomerField;
            }
            set {
                this.noOfCustomerField = value;
                this.RaisePropertyChanged("NoOfCustomer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string MemberLevelCode {
            get {
                return this.memberLevelCodeField;
            }
            set {
                this.memberLevelCodeField = value;
                this.RaisePropertyChanged("MemberLevelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public System.DateTime FirstLoanDate {
            get {
                return this.firstLoanDateField;
            }
            set {
                this.firstLoanDateField = value;
                this.RaisePropertyChanged("FirstLoanDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public int NoOfLoans {
            get {
                return this.noOfLoansField;
            }
            set {
                this.noOfLoansField = value;
                this.RaisePropertyChanged("NoOfLoans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string HubCode {
            get {
                return this.hubCodeField;
            }
            set {
                this.hubCodeField = value;
                this.RaisePropertyChanged("HubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public double HighestDeposit {
            get {
                return this.highestDepositField;
            }
            set {
                this.highestDepositField = value;
                this.RaisePropertyChanged("HighestDeposit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public double CurrentDeposit {
            get {
                return this.currentDepositField;
            }
            set {
                this.currentDepositField = value;
                this.RaisePropertyChanged("CurrentDeposit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public double TotalAmtLoans {
            get {
                return this.totalAmtLoansField;
            }
            set {
                this.totalAmtLoansField = value;
                this.RaisePropertyChanged("TotalAmtLoans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public double CurrentLoanOutstanding {
            get {
                return this.currentLoanOutstandingField;
            }
            set {
                this.currentLoanOutstandingField = value;
                this.RaisePropertyChanged("CurrentLoanOutstanding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public double OnTimePayment {
            get {
                return this.onTimePaymentField;
            }
            set {
                this.onTimePaymentField = value;
                this.RaisePropertyChanged("OnTimePayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public System.DateTime CloseDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
                this.RaisePropertyChanged("CloseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public double OverPay {
            get {
                return this.overPayField;
            }
            set {
                this.overPayField = value;
                this.RaisePropertyChanged("OverPay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public double UnderPay {
            get {
                return this.underPayField;
            }
            set {
                this.underPayField = value;
                this.RaisePropertyChanged("UnderPay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string SMETypeCode {
            get {
                return this.sMETypeCodeField;
            }
            set {
                this.sMETypeCodeField = value;
                this.RaisePropertyChanged("SMETypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string SMEGroupCode {
            get {
                return this.sMEGroupCodeField;
            }
            set {
                this.sMEGroupCodeField = value;
                this.RaisePropertyChanged("SMEGroupCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string StoreLocationCode {
            get {
                return this.storeLocationCodeField;
            }
            set {
                this.storeLocationCodeField = value;
                this.RaisePropertyChanged("StoreLocationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string VendorTypeCode {
            get {
                return this.vendorTypeCodeField;
            }
            set {
                this.vendorTypeCodeField = value;
                this.RaisePropertyChanged("VendorTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string TradeTypeCode {
            get {
                return this.tradeTypeCodeField;
            }
            set {
                this.tradeTypeCodeField = value;
                this.RaisePropertyChanged("TradeTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string VerifyStatusBranch {
            get {
                return this.verifyStatusBranchField;
            }
            set {
                this.verifyStatusBranchField = value;
                this.RaisePropertyChanged("VerifyStatusBranch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string VerifyStatusHub {
            get {
                return this.verifyStatusHubField;
            }
            set {
                this.verifyStatusHubField = value;
                this.RaisePropertyChanged("VerifyStatusHub");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public int VSBranchUserId {
            get {
                return this.vSBranchUserIdField;
            }
            set {
                this.vSBranchUserIdField = value;
                this.RaisePropertyChanged("VSBranchUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public int VSHubUserId {
            get {
                return this.vSHubUserIdField;
            }
            set {
                this.vSHubUserIdField = value;
                this.RaisePropertyChanged("VSHubUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public System.DateTime VSBranchDate {
            get {
                return this.vSBranchDateField;
            }
            set {
                this.vSBranchDateField = value;
                this.RaisePropertyChanged("VSBranchDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public System.DateTime VSHubDate {
            get {
                return this.vSHubDateField;
            }
            set {
                this.vSHubDateField = value;
                this.RaisePropertyChanged("VSHubDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=61)]
        public byte[] FacePic {
            get {
                return this.facePicField;
            }
            set {
                this.facePicField = value;
                this.RaisePropertyChanged("FacePic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=62)]
        public byte[] Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=63)]
        public byte[] NRCBackPic {
            get {
                return this.nRCBackPicField;
            }
            set {
                this.nRCBackPicField = value;
                this.RaisePropertyChanged("NRCBackPic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=64)]
        public byte[] NRCFrontPic {
            get {
                return this.nRCFrontPicField;
            }
            set {
                this.nRCFrontPicField = value;
                this.RaisePropertyChanged("NRCFrontPic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=65)]
        public byte[] LandTitleDeedPic {
            get {
                return this.landTitleDeedPicField;
            }
            set {
                this.landTitleDeedPicField = value;
                this.RaisePropertyChanged("LandTitleDeedPic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=66)]
        public byte[] HouseHoldRegisPic {
            get {
                return this.houseHoldRegisPicField;
            }
            set {
                this.houseHoldRegisPicField = value;
                this.RaisePropertyChanged("HouseHoldRegisPic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TimeSpan : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string branchCodeField;
        
        private byte[] fingerPrint1Field;
        
        private byte[] fingerPrint2Field;
        
        private bool isMultiUserField;
        
        private bool isLogonField;
        
        private string fullNameField;
        
        private string emailField;
        
        private bool isNextLogonPasswordChangedField;
        
        private bool canPasswordChangedField;
        
        private bool canPasswordExpiredField;
        
        private bool isPasswordExpiredField;
        
        private System.Nullable<System.DateTime> passwordExpiredDateField;
        
        private bool isAccountDisabledField;
        
        private int failedPasswordAttemptCountField;
        
        private System.Nullable<System.DateTime> failedPasswordAttemptWindowStartField;
        
        private System.Nullable<System.DateTime> lastAccountDisabledDateField;
        
        private System.Nullable<System.DateTime> lastLogInDateField;
        
        private System.Nullable<System.DateTime> lastLogOffDateField;
        
        private bool activeField;
        
        private TimeSpan tsField;
        
        private System.DateTime createdDateField;
        
        private int createdUserIdField;
        
        private System.DateTime updatedDateField;
        
        private int updatedUserIdField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] FingerPrint1 {
            get {
                return this.fingerPrint1Field;
            }
            set {
                this.fingerPrint1Field = value;
                this.RaisePropertyChanged("FingerPrint1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] FingerPrint2 {
            get {
                return this.fingerPrint2Field;
            }
            set {
                this.fingerPrint2Field = value;
                this.RaisePropertyChanged("FingerPrint2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsMultiUser {
            get {
                return this.isMultiUserField;
            }
            set {
                this.isMultiUserField = value;
                this.RaisePropertyChanged("IsMultiUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsLogon {
            get {
                return this.isLogonField;
            }
            set {
                this.isLogonField = value;
                this.RaisePropertyChanged("IsLogon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsNextLogonPasswordChanged {
            get {
                return this.isNextLogonPasswordChangedField;
            }
            set {
                this.isNextLogonPasswordChangedField = value;
                this.RaisePropertyChanged("IsNextLogonPasswordChanged");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool CanPasswordChanged {
            get {
                return this.canPasswordChangedField;
            }
            set {
                this.canPasswordChangedField = value;
                this.RaisePropertyChanged("CanPasswordChanged");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool CanPasswordExpired {
            get {
                return this.canPasswordExpiredField;
            }
            set {
                this.canPasswordExpiredField = value;
                this.RaisePropertyChanged("CanPasswordExpired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsPasswordExpired {
            get {
                return this.isPasswordExpiredField;
            }
            set {
                this.isPasswordExpiredField = value;
                this.RaisePropertyChanged("IsPasswordExpired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> PasswordExpiredDate {
            get {
                return this.passwordExpiredDateField;
            }
            set {
                this.passwordExpiredDateField = value;
                this.RaisePropertyChanged("PasswordExpiredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsAccountDisabled {
            get {
                return this.isAccountDisabledField;
            }
            set {
                this.isAccountDisabledField = value;
                this.RaisePropertyChanged("IsAccountDisabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int FailedPasswordAttemptCount {
            get {
                return this.failedPasswordAttemptCountField;
            }
            set {
                this.failedPasswordAttemptCountField = value;
                this.RaisePropertyChanged("FailedPasswordAttemptCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> FailedPasswordAttemptWindowStart {
            get {
                return this.failedPasswordAttemptWindowStartField;
            }
            set {
                this.failedPasswordAttemptWindowStartField = value;
                this.RaisePropertyChanged("FailedPasswordAttemptWindowStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> LastAccountDisabledDate {
            get {
                return this.lastAccountDisabledDateField;
            }
            set {
                this.lastAccountDisabledDateField = value;
                this.RaisePropertyChanged("LastAccountDisabledDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<System.DateTime> LastLogInDate {
            get {
                return this.lastLogInDateField;
            }
            set {
                this.lastLogInDateField = value;
                this.RaisePropertyChanged("LastLogInDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<System.DateTime> LastLogOffDate {
            get {
                return this.lastLogOffDateField;
            }
            set {
                this.lastLogOffDateField = value;
                this.RaisePropertyChanged("LastLogOffDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public TimeSpan TS {
            get {
                return this.tsField;
            }
            set {
                this.tsField = value;
                this.RaisePropertyChanged("TS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int CreatedUserId {
            get {
                return this.createdUserIdField;
            }
            set {
                this.createdUserIdField = value;
                this.RaisePropertyChanged("CreatedUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public System.DateTime UpdatedDate {
            get {
                return this.updatedDateField;
            }
            set {
                this.updatedDateField = value;
                this.RaisePropertyChanged("UpdatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int UpdatedUserId {
            get {
                return this.updatedUserIdField;
            }
            set {
                this.updatedUserIdField = value;
                this.RaisePropertyChanged("UpdatedUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string branchCodeField;
        
        private byte[] fingerPrintField;
        
        private UserType statusField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] FingerPrint {
            get {
                return this.fingerPrintField;
            }
            set {
                this.fingerPrintField = value;
                this.RaisePropertyChanged("FingerPrint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UserType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum UserType {
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        User,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerVerifiedLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CustomerVerifiedLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string branchCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fingerPrint;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string customerid;
        
        public CustomerVerifiedLoginRequest() {
        }
        
        public CustomerVerifiedLoginRequest(string branchCode, byte[] fingerPrint, string customerid) {
            this.branchCode = branchCode;
            this.fingerPrint = fingerPrint;
            this.customerid = customerid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerVerifiedLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CustomerVerifiedLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CustomerVerifiedLoginResult;
        
        public CustomerVerifiedLoginResponse() {
        }
        
        public CustomerVerifiedLoginResponse(bool CustomerVerifiedLoginResult) {
            this.CustomerVerifiedLoginResult = CustomerVerifiedLoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RouteWebServiceSoapChannel : MahaAwbaWCF.RouteWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteWebServiceSoapClient : System.ServiceModel.ClientBase<MahaAwbaWCF.RouteWebServiceSoap>, MahaAwbaWCF.RouteWebServiceSoap {
        
        public RouteWebServiceSoapClient() {
        }
        
        public RouteWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode MobileLogin(string xmlData) {
            return base.Channel.MobileLogin(xmlData);
        }
        
        public System.Data.DataSet GetServerLog(string branchCode) {
            return base.Channel.GetServerLog(branchCode);
        }
        
        public string GetRepaymentInquiryInfo(string xmlData) {
            return base.Channel.GetRepaymentInquiryInfo(xmlData);
        }
        
        public string GetRepaymentComfirmation(string xmlData) {
            return base.Channel.GetRepaymentComfirmation(xmlData);
        }
        
        public bool AddDisbursement(string xmlData) {
            return base.Channel.AddDisbursement(xmlData);
        }
        
        public bool AddSurveyVillageForMobile(string xmlData) {
            return base.Channel.AddSurveyVillageForMobile(xmlData);
        }
        
        public bool AddTownSurveyForMobile(string xmlData) {
            return base.Channel.AddTownSurveyForMobile(xmlData);
        }
        
        public bool AddSMESurveyForMobile(string xmlData) {
            return base.Channel.AddSMESurveyForMobile(xmlData);
        }
        
        public bool AddCustRegVendorForMobile(string xmlData) {
            return base.Channel.AddCustRegVendorForMobile(xmlData);
        }
        
        public bool AddCustRegFarmerForMobile(string xmlData) {
            return base.Channel.AddCustRegFarmerForMobile(xmlData);
        }
        
        public bool AddLoanApplicationFarmerForMobile(string xmlData) {
            return base.Channel.AddLoanApplicationFarmerForMobile(xmlData);
        }
        
        public bool AddLoanApplicationVendorForMobile(string xmlData) {
            return base.Channel.AddLoanApplicationVendorForMobile(xmlData);
        }
        
        public System.Xml.XmlNode GetVerifiedSurveySME(string xmldata) {
            return base.Channel.GetVerifiedSurveySME(xmldata);
        }
        
        public System.Xml.XmlNode GetAllUserDataByBranch(string xmldata) {
            return base.Channel.GetAllUserDataByBranch(xmldata);
        }
        
        public System.Xml.XmlNode GetMasterData(string xmldata) {
            return base.Channel.GetMasterData(xmldata);
        }
        
        public System.Xml.XmlNode GetAllLoanProductType(string xmldata) {
            return base.Channel.GetAllLoanProductType(xmldata);
        }
        
        public System.Xml.XmlNode GetAllDisbursementData(string xmldata) {
            return base.Channel.GetAllDisbursementData(xmldata);
        }
        
        public System.Xml.XmlNode GetAllLoanProductTypeItem(string xmldata) {
            return base.Channel.GetAllLoanProductTypeItem(xmldata);
        }
        
        public System.Xml.XmlNode GetAllMicroLoan(string xmldata) {
            return base.Channel.GetAllMicroLoan(xmldata);
        }
        
        public System.Xml.XmlNode GetAllMicroTerm(string xmldata) {
            return base.Channel.GetAllMicroTerm(xmldata);
        }
        
        public System.Xml.XmlNode GetVerifiedSurveyTown(string xmldata) {
            return base.Channel.GetVerifiedSurveyTown(xmldata);
        }
        
        public System.Xml.XmlNode GetVerifiedSurveyFarmVillage(string xmldata) {
            return base.Channel.GetVerifiedSurveyFarmVillage(xmldata);
        }
        
        public System.Xml.XmlNode GetVerifiedCustRegFarmer(string xmldata) {
            return base.Channel.GetVerifiedCustRegFarmer(xmldata);
        }
        
        public System.Xml.XmlNode GetVerifiedCustRegVendor(string xmldata) {
            return base.Channel.GetVerifiedCustRegVendor(xmldata);
        }
        
        public System.Xml.XmlNode GetVerifiedLoanAppFarmer(string xmldata) {
            return base.Channel.GetVerifiedLoanAppFarmer(xmldata);
        }
        
        public System.Xml.XmlNode GetVerifiedLoanAppVendor(string xmldata) {
            return base.Channel.GetVerifiedLoanAppVendor(xmldata);
        }
        
        public System.Data.DataSet GetUserDataForFingerPrint(MahaAwbaWCF.RequestParameter para) {
            return base.Channel.GetUserDataForFingerPrint(para);
        }
        
        public int DesktopLogin(MahaAwbaWCF.UserAccount user) {
            return base.Channel.DesktopLogin(user);
        }
        
        public bool VerifiedCustomer(MahaAwbaWCF.UserAccount user) {
            return base.Channel.VerifiedCustomer(user);
        }
        
        public System.Data.DataSet GetCustomerDataForFingerPrint(MahaAwbaWCF.RequestParameter para) {
            return base.Channel.GetCustomerDataForFingerPrint(para);
        }
        
        public bool AddUserForDesktop(MahaAwbaWCF.User user) {
            return base.Channel.AddUserForDesktop(user);
        }
        
        public bool AddCustomerForDesktop(MahaAwbaWCF.Customer customer) {
            return base.Channel.AddCustomerForDesktop(customer);
        }
        
        public bool UpdateCustomerForDesktop(MahaAwbaWCF.Customer customer) {
            return base.Channel.UpdateCustomerForDesktop(customer);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MahaAwbaWCF.CustomerVerifiedLoginResponse MahaAwbaWCF.RouteWebServiceSoap.CustomerVerifiedLogin(MahaAwbaWCF.CustomerVerifiedLoginRequest request) {
            return base.Channel.CustomerVerifiedLogin(request);
        }
        
        public bool CustomerVerifiedLogin(string branchCode, byte[] fingerPrint, string customerid) {
            MahaAwbaWCF.CustomerVerifiedLoginRequest inValue = new MahaAwbaWCF.CustomerVerifiedLoginRequest();
            inValue.branchCode = branchCode;
            inValue.fingerPrint = fingerPrint;
            inValue.customerid = customerid;
            MahaAwbaWCF.CustomerVerifiedLoginResponse retVal = ((MahaAwbaWCF.RouteWebServiceSoap)(this)).CustomerVerifiedLogin(inValue);
            return retVal.CustomerVerifiedLoginResult;
        }
        
        public bool AddUser(MahaAwbaWCF.User para) {
            return base.Channel.AddUser(para);
        }
        
        public System.Data.DataSet AddtestData(string name, string serverName, string ipAddress, string userId, string password) {
            return base.Channel.AddtestData(name, serverName, ipAddress, userId, password);
        }
    }
}
