//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="smsWCF.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        smsWCF.CompositeType GetDataUsingDataContract(smsWCF.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendSMS", ReplyAction="http://tempuri.org/IService/sendSMSResponse")]
        bool sendSMS(string mobileNumber, string smsMessage, string senderName, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendSMSWithTxnID", ReplyAction="http://tempuri.org/IService/sendSMSWithTxnIDResponse")]
        bool sendSMSWithTxnID(string mobileNumber, string smsMessage, string language, long txnID, string smsSenderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AGDSendSms", ReplyAction="http://tempuri.org/IService/AGDSendSmsResponse")]
        string AGDSendSms(string teleNo, string smsMessage, string smsSenderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AGDSendSmsWithTxnId", ReplyAction="http://tempuri.org/IService/AGDSendSmsWithTxnIdResponse")]
        string AGDSendSmsWithTxnId(string teleNo, string smsMessage, string smsSenderName, long txnID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendSmsWithTxnIdLB", ReplyAction="http://tempuri.org/IService/sendSmsWithTxnIdLBResponse")]
        string sendSmsWithTxnIdLB(string teleNo, string smsMessage, string smsSenderName, long txnID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateSmsStatusSolarHome", ReplyAction="http://tempuri.org/IService/UpdateSmsStatusSolarHomeResponse")]
        bool UpdateSmsStatusSolarHome(out string errMsg, long txnID, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : smsWCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<smsWCF.IService>, smsWCF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public smsWCF.CompositeType GetDataUsingDataContract(smsWCF.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public bool sendSMS(string mobileNumber, string smsMessage, string senderName, string language) {
            return base.Channel.sendSMS(mobileNumber, smsMessage, senderName, language);
        }
        
        public bool sendSMSWithTxnID(string mobileNumber, string smsMessage, string language, long txnID, string smsSenderName) {
            return base.Channel.sendSMSWithTxnID(mobileNumber, smsMessage, language, txnID, smsSenderName);
        }
        
        public string AGDSendSms(string teleNo, string smsMessage, string smsSenderName) {
            return base.Channel.AGDSendSms(teleNo, smsMessage, smsSenderName);
        }
        
        public string AGDSendSmsWithTxnId(string teleNo, string smsMessage, string smsSenderName, long txnID) {
            return base.Channel.AGDSendSmsWithTxnId(teleNo, smsMessage, smsSenderName, txnID);
        }
        
        public string sendSmsWithTxnIdLB(string teleNo, string smsMessage, string smsSenderName, long txnID) {
            return base.Channel.sendSmsWithTxnIdLB(teleNo, smsMessage, smsSenderName, txnID);
        }
        
        public bool UpdateSmsStatusSolarHome(out string errMsg, long txnID, string status) {
            return base.Channel.UpdateSmsStatusSolarHome(out errMsg, txnID, status);
        }
    }
}
