//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopupService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationRequest", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class AuthenticationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialUserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialPassword {
            get {
                return this.CredentialPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialPasswordField, value) != true)) {
                    this.CredentialPasswordField = value;
                    this.RaisePropertyChanged("CredentialPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialUserName {
            get {
                return this.CredentialUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialUserNameField, value) != true)) {
                    this.CredentialUserNameField = value;
                    this.RaisePropertyChanged("CredentialUserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResellerAPITokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResellerAPIToken {
            get {
                return this.ResellerAPITokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ResellerAPITokenField, value) != true)) {
                    this.ResellerAPITokenField = value;
                    this.RaisePropertyChanged("ResellerAPIToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrepaidCardResellerRequest", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class PrepaidCardResellerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResellerAPITokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResellerIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPrice {
            get {
                return this.CardPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPriceField, value) != true)) {
                    this.CardPriceField = value;
                    this.RaisePropertyChanged("CardPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialPassword {
            get {
                return this.CredentialPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialPasswordField, value) != true)) {
                    this.CredentialPasswordField = value;
                    this.RaisePropertyChanged("CredentialPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialUserName {
            get {
                return this.CredentialUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialUserNameField, value) != true)) {
                    this.CredentialUserNameField = value;
                    this.RaisePropertyChanged("CredentialUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResellerAPIToken {
            get {
                return this.ResellerAPITokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ResellerAPITokenField, value) != true)) {
                    this.ResellerAPITokenField = value;
                    this.RaisePropertyChanged("ResellerAPIToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResellerID {
            get {
                return this.ResellerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ResellerIDField, value) != true)) {
                    this.ResellerIDField = value;
                    this.RaisePropertyChanged("ResellerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrepaidCardResellerResponse", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class PrepaidCardResellerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResellerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellingPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiredDate {
            get {
                return this.ExpiredDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiredDateField, value) != true)) {
                    this.ExpiredDateField = value;
                    this.RaisePropertyChanged("ExpiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceIDField, value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PinNumber {
            get {
                return this.PinNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PinNumberField, value) != true)) {
                    this.PinNumberField = value;
                    this.RaisePropertyChanged("PinNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResellerID {
            get {
                return this.ResellerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ResellerIDField, value) != true)) {
                    this.ResellerIDField = value;
                    this.RaisePropertyChanged("ResellerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellingPrice {
            get {
                return this.SellingPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingPriceField, value) != true)) {
                    this.SellingPriceField = value;
                    this.RaisePropertyChanged("SellingPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardPriceEnquiryRequest", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class CardPriceEnquiryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialUserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPrice {
            get {
                return this.CardPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPriceField, value) != true)) {
                    this.CardPriceField = value;
                    this.RaisePropertyChanged("CardPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialPassword {
            get {
                return this.CredentialPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialPasswordField, value) != true)) {
                    this.CredentialPasswordField = value;
                    this.RaisePropertyChanged("CredentialPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialUserName {
            get {
                return this.CredentialUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialUserNameField, value) != true)) {
                    this.CredentialUserNameField = value;
                    this.RaisePropertyChanged("CredentialUserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardPriceEnquiryResponse", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class CardPriceEnquiryResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActualCardPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsOutOfStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LastestCardPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualCardPrice {
            get {
                return this.ActualCardPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualCardPriceField, value) != true)) {
                    this.ActualCardPriceField = value;
                    this.RaisePropertyChanged("ActualCardPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsOutOfStock {
            get {
                return this.IsOutOfStockField;
            }
            set {
                if ((object.ReferenceEquals(this.IsOutOfStockField, value) != true)) {
                    this.IsOutOfStockField = value;
                    this.RaisePropertyChanged("IsOutOfStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LastestCardPrice {
            get {
                return this.LastestCardPriceField;
            }
            set {
                if ((this.LastestCardPriceField.Equals(value) != true)) {
                    this.LastestCardPriceField = value;
                    this.RaisePropertyChanged("LastestCardPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopUpRequest", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class TopUpRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopUpAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialPassword {
            get {
                return this.CredentialPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialPasswordField, value) != true)) {
                    this.CredentialPasswordField = value;
                    this.RaisePropertyChanged("CredentialPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialUserName {
            get {
                return this.CredentialUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialUserNameField, value) != true)) {
                    this.CredentialUserNameField = value;
                    this.RaisePropertyChanged("CredentialUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopUpAmount {
            get {
                return this.TopUpAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.TopUpAmountField, value) != true)) {
                    this.TopUpAmountField = value;
                    this.RaisePropertyChanged("TopUpAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopUpResponse", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class TopUpResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueResellerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string UniqueResellerID {
            get {
                return this.UniqueResellerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueResellerIDField, value) != true)) {
                    this.UniqueResellerIDField = value;
                    this.RaisePropertyChanged("UniqueResellerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InquiryQRequest", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class InquiryQRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InquiryQResponse", Namespace="http://schemas.datacontract.org/2004/07/PrepaidCardResellerCore.Domain")]
    [System.SerializableAttribute()]
    public partial class InquiryQResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryReport {
            get {
                return this.DeliveryReportField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryReportField, value) != true)) {
                    this.DeliveryReportField = value;
                    this.RaisePropertyChanged("DeliveryReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryStatus {
            get {
                return this.DeliveryStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryStatusField, value) != true)) {
                    this.DeliveryStatusField = value;
                    this.RaisePropertyChanged("DeliveryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNumberField, value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TopupService.IResellerService")]
    public interface IResellerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/AuthenticationAPI", ReplyAction="http://tempuri.org/IResellerService/AuthenticationAPIResponse")]
        TopupService.AuthenticationResponse AuthenticationAPI(TopupService.AuthenticationRequest authenticationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/AuthenticationAPI", ReplyAction="http://tempuri.org/IResellerService/AuthenticationAPIResponse")]
        System.Threading.Tasks.Task<TopupService.AuthenticationResponse> AuthenticationAPIAsync(TopupService.AuthenticationRequest authenticationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/SoldOutPrepaidCard", ReplyAction="http://tempuri.org/IResellerService/SoldOutPrepaidCardResponse")]
        TopupService.PrepaidCardResellerResponse SoldOutPrepaidCard(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/SoldOutPrepaidCard", ReplyAction="http://tempuri.org/IResellerService/SoldOutPrepaidCardResponse")]
        System.Threading.Tasks.Task<TopupService.PrepaidCardResellerResponse> SoldOutPrepaidCardAsync(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/SoldOutPrepaidCardNew", ReplyAction="http://tempuri.org/IResellerService/SoldOutPrepaidCardNewResponse")]
        TopupService.PrepaidCardResellerResponse SoldOutPrepaidCardNew(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/SoldOutPrepaidCardNew", ReplyAction="http://tempuri.org/IResellerService/SoldOutPrepaidCardNewResponse")]
        System.Threading.Tasks.Task<TopupService.PrepaidCardResellerResponse> SoldOutPrepaidCardNewAsync(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/SoldOutPrepaidCard2", ReplyAction="http://tempuri.org/IResellerService/SoldOutPrepaidCard2Response")]
        TopupService.PrepaidCardResellerResponse SoldOutPrepaidCard2(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/SoldOutPrepaidCard2", ReplyAction="http://tempuri.org/IResellerService/SoldOutPrepaidCard2Response")]
        System.Threading.Tasks.Task<TopupService.PrepaidCardResellerResponse> SoldOutPrepaidCard2Async(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/EnquiryLastestCardPrice", ReplyAction="http://tempuri.org/IResellerService/EnquiryLastestCardPriceResponse")]
        TopupService.CardPriceEnquiryResponse EnquiryLastestCardPrice(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/EnquiryLastestCardPrice", ReplyAction="http://tempuri.org/IResellerService/EnquiryLastestCardPriceResponse")]
        System.Threading.Tasks.Task<TopupService.CardPriceEnquiryResponse> EnquiryLastestCardPriceAsync(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/EnquiryLastestCardPrice2", ReplyAction="http://tempuri.org/IResellerService/EnquiryLastestCardPrice2Response")]
        TopupService.CardPriceEnquiryResponse EnquiryLastestCardPrice2(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/EnquiryLastestCardPrice2", ReplyAction="http://tempuri.org/IResellerService/EnquiryLastestCardPrice2Response")]
        System.Threading.Tasks.Task<TopupService.CardPriceEnquiryResponse> EnquiryLastestCardPrice2Async(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/QuickTopUp", ReplyAction="http://tempuri.org/IResellerService/QuickTopUpResponse")]
        TopupService.TopUpResponse QuickTopUp(TopupService.TopUpRequest topupRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/QuickTopUp", ReplyAction="http://tempuri.org/IResellerService/QuickTopUpResponse")]
        System.Threading.Tasks.Task<TopupService.TopUpResponse> QuickTopUpAsync(TopupService.TopUpRequest topupRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/InquiryTopUp", ReplyAction="http://tempuri.org/IResellerService/InquiryTopUpResponse")]
        TopupService.InquiryQResponse InquiryTopUp(TopupService.InquiryQRequest topupRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResellerService/InquiryTopUp", ReplyAction="http://tempuri.org/IResellerService/InquiryTopUpResponse")]
        System.Threading.Tasks.Task<TopupService.InquiryQResponse> InquiryTopUpAsync(TopupService.InquiryQRequest topupRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResellerServiceChannel : TopupService.IResellerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResellerServiceClient : System.ServiceModel.ClientBase<TopupService.IResellerService>, TopupService.IResellerService {
        
        public ResellerServiceClient() {
        }
        
        public ResellerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResellerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResellerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResellerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TopupService.AuthenticationResponse AuthenticationAPI(TopupService.AuthenticationRequest authenticationRequest) {
            return base.Channel.AuthenticationAPI(authenticationRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.AuthenticationResponse> AuthenticationAPIAsync(TopupService.AuthenticationRequest authenticationRequest) {
            return base.Channel.AuthenticationAPIAsync(authenticationRequest);
        }
        
        public TopupService.PrepaidCardResellerResponse SoldOutPrepaidCard(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest) {
            return base.Channel.SoldOutPrepaidCard(prepaidcardResellerRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.PrepaidCardResellerResponse> SoldOutPrepaidCardAsync(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest) {
            return base.Channel.SoldOutPrepaidCardAsync(prepaidcardResellerRequest);
        }
        
        public TopupService.PrepaidCardResellerResponse SoldOutPrepaidCardNew(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest) {
            return base.Channel.SoldOutPrepaidCardNew(prepaidcardResellerRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.PrepaidCardResellerResponse> SoldOutPrepaidCardNewAsync(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest) {
            return base.Channel.SoldOutPrepaidCardNewAsync(prepaidcardResellerRequest);
        }
        
        public TopupService.PrepaidCardResellerResponse SoldOutPrepaidCard2(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest) {
            return base.Channel.SoldOutPrepaidCard2(prepaidcardResellerRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.PrepaidCardResellerResponse> SoldOutPrepaidCard2Async(TopupService.PrepaidCardResellerRequest prepaidcardResellerRequest) {
            return base.Channel.SoldOutPrepaidCard2Async(prepaidcardResellerRequest);
        }
        
        public TopupService.CardPriceEnquiryResponse EnquiryLastestCardPrice(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest) {
            return base.Channel.EnquiryLastestCardPrice(cardPriceEnquiryRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.CardPriceEnquiryResponse> EnquiryLastestCardPriceAsync(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest) {
            return base.Channel.EnquiryLastestCardPriceAsync(cardPriceEnquiryRequest);
        }
        
        public TopupService.CardPriceEnquiryResponse EnquiryLastestCardPrice2(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest) {
            return base.Channel.EnquiryLastestCardPrice2(cardPriceEnquiryRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.CardPriceEnquiryResponse> EnquiryLastestCardPrice2Async(TopupService.CardPriceEnquiryRequest cardPriceEnquiryRequest) {
            return base.Channel.EnquiryLastestCardPrice2Async(cardPriceEnquiryRequest);
        }
        
        public TopupService.TopUpResponse QuickTopUp(TopupService.TopUpRequest topupRequest) {
            return base.Channel.QuickTopUp(topupRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.TopUpResponse> QuickTopUpAsync(TopupService.TopUpRequest topupRequest) {
            return base.Channel.QuickTopUpAsync(topupRequest);
        }
        
        public TopupService.InquiryQResponse InquiryTopUp(TopupService.InquiryQRequest topupRequest) {
            return base.Channel.InquiryTopUp(topupRequest);
        }
        
        public System.Threading.Tasks.Task<TopupService.InquiryQResponse> InquiryTopUpAsync(TopupService.InquiryQRequest topupRequest) {
            return base.Channel.InquiryTopUpAsync(topupRequest);
        }
    }
}
