//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwsEmailAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AwsEmailAPI.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name fromDisplayName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMail", ReplyAction="*")]
        AwsEmailAPI.sendMailResponse sendMail(AwsEmailAPI.sendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendMailResponse> sendMailAsync(AwsEmailAPI.sendMailRequest request);
        
        // CODEGEN: Generating message contract since element name fromEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMailCDONTS", ReplyAction="*")]
        AwsEmailAPI.sendMailCDONTSResponse sendMailCDONTS(AwsEmailAPI.sendMailCDONTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendMailCDONTS", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendMailCDONTSResponse> sendMailCDONTSAsync(AwsEmailAPI.sendMailCDONTSRequest request);
        
        // CODEGEN: Generating message contract since element name fromEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendGridMail", ReplyAction="*")]
        AwsEmailAPI.sendGridMailResponse sendGridMail(AwsEmailAPI.sendGridMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendGridMail", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendGridMailResponse> sendGridMailAsync(AwsEmailAPI.sendGridMailRequest request);
        
        // CODEGEN: Generating message contract since element name fromEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendGridMailWithCategory", ReplyAction="*")]
        AwsEmailAPI.sendGridMailWithCategoryResponse sendGridMailWithCategory(AwsEmailAPI.sendGridMailWithCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendGridMailWithCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendGridMailWithCategoryResponse> sendGridMailWithCategoryAsync(AwsEmailAPI.sendGridMailWithCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name fromEmail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendAWSMail", ReplyAction="*")]
        AwsEmailAPI.sendAWSMailResponse sendAWSMail(AwsEmailAPI.sendAWSMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendAWSMail", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendAWSMailResponse> sendAWSMailAsync(AwsEmailAPI.sendAWSMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendGridEmailwihtAttached", ReplyAction="*")]
        AwsEmailAPI.sendGridEmailwihtAttachedResponse sendGridEmailwihtAttached(AwsEmailAPI.sendGridEmailwihtAttachedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendGridEmailwihtAttached", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendGridEmailwihtAttachedResponse> sendGridEmailwihtAttachedAsync(AwsEmailAPI.sendGridEmailwihtAttachedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailByteArrayAttached", ReplyAction="*")]
        AwsEmailAPI.sendEmailByteArrayAttachedResponse sendEmailByteArrayAttached(AwsEmailAPI.sendEmailByteArrayAttachedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailByteArrayAttached", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendEmailByteArrayAttachedResponse> sendEmailByteArrayAttachedAsync(AwsEmailAPI.sendEmailByteArrayAttachedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailEmbededImage", ReplyAction="*")]
        AwsEmailAPI.sendEmailEmbededImageResponse sendEmailEmbededImage(AwsEmailAPI.sendEmailEmbededImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailEmbededImage", ReplyAction="*")]
        System.Threading.Tasks.Task<AwsEmailAPI.sendEmailEmbededImageResponse> sendEmailEmbededImageAsync(AwsEmailAPI.sendEmailEmbededImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMail", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendMailRequestBody Body;
        
        public sendMailRequest() {
        }
        
        public sendMailRequest(AwsEmailAPI.sendMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string body;
        
        public sendMailRequestBody() {
        }
        
        public sendMailRequestBody(string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            this.fromDisplayName = fromDisplayName;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendMailResponseBody Body;
        
        public sendMailResponse() {
        }
        
        public sendMailResponse(AwsEmailAPI.sendMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendMailResult;
        
        public sendMailResponseBody() {
        }
        
        public sendMailResponseBody(bool sendMailResult) {
            this.sendMailResult = sendMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMailCDONTSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMailCDONTS", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendMailCDONTSRequestBody Body;
        
        public sendMailCDONTSRequest() {
        }
        
        public sendMailCDONTSRequest(AwsEmailAPI.sendMailCDONTSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMailCDONTSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string body;
        
        public sendMailCDONTSRequestBody() {
        }
        
        public sendMailCDONTSRequestBody(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            this.fromEmail = fromEmail;
            this.fromDisplayName = fromDisplayName;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMailCDONTSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMailCDONTSResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendMailCDONTSResponseBody Body;
        
        public sendMailCDONTSResponse() {
        }
        
        public sendMailCDONTSResponse(AwsEmailAPI.sendMailCDONTSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendMailCDONTSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendMailCDONTSResult;
        
        public sendMailCDONTSResponseBody() {
        }
        
        public sendMailCDONTSResponseBody(bool sendMailCDONTSResult) {
            this.sendMailCDONTSResult = sendMailCDONTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGridMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGridMail", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendGridMailRequestBody Body;
        
        public sendGridMailRequest() {
        }
        
        public sendGridMailRequest(AwsEmailAPI.sendGridMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendGridMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string body;
        
        public sendGridMailRequestBody() {
        }
        
        public sendGridMailRequestBody(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            this.fromEmail = fromEmail;
            this.fromDisplayName = fromDisplayName;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGridMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGridMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendGridMailResponseBody Body;
        
        public sendGridMailResponse() {
        }
        
        public sendGridMailResponse(AwsEmailAPI.sendGridMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendGridMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendGridMailResult;
        
        public sendGridMailResponseBody() {
        }
        
        public sendGridMailResponseBody(bool sendGridMailResult) {
            this.sendGridMailResult = sendGridMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGridMailWithCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGridMailWithCategory", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendGridMailWithCategoryRequestBody Body;
        
        public sendGridMailWithCategoryRequest() {
        }
        
        public sendGridMailWithCategoryRequest(AwsEmailAPI.sendGridMailWithCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendGridMailWithCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strCategory;
        
        public sendGridMailWithCategoryRequestBody() {
        }
        
        public sendGridMailWithCategoryRequestBody(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body, string strCategory) {
            this.fromEmail = fromEmail;
            this.fromDisplayName = fromDisplayName;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
            this.strCategory = strCategory;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGridMailWithCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGridMailWithCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendGridMailWithCategoryResponseBody Body;
        
        public sendGridMailWithCategoryResponse() {
        }
        
        public sendGridMailWithCategoryResponse(AwsEmailAPI.sendGridMailWithCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendGridMailWithCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendGridMailWithCategoryResult;
        
        public sendGridMailWithCategoryResponseBody() {
        }
        
        public sendGridMailWithCategoryResponseBody(bool sendGridMailWithCategoryResult) {
            this.sendGridMailWithCategoryResult = sendGridMailWithCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAWSMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAWSMail", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendAWSMailRequestBody Body;
        
        public sendAWSMailRequest() {
        }
        
        public sendAWSMailRequest(AwsEmailAPI.sendAWSMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendAWSMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fromDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string body;
        
        public sendAWSMailRequestBody() {
        }
        
        public sendAWSMailRequestBody(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            this.fromEmail = fromEmail;
            this.fromDisplayName = fromDisplayName;
            this.to = to;
            this.cc = cc;
            this.bcc = bcc;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendAWSMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendAWSMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendAWSMailResponseBody Body;
        
        public sendAWSMailResponse() {
        }
        
        public sendAWSMailResponse(AwsEmailAPI.sendAWSMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendAWSMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendAWSMailResult;
        
        public sendAWSMailResponseBody() {
        }
        
        public sendAWSMailResponseBody(bool sendAWSMailResult) {
            this.sendAWSMailResult = sendAWSMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGridEmailwihtAttachedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGridEmailwihtAttached", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendGridEmailwihtAttachedRequestBody Body;
        
        public sendGridEmailwihtAttachedRequest() {
        }
        
        public sendGridEmailwihtAttachedRequest(AwsEmailAPI.sendGridEmailwihtAttachedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendGridEmailwihtAttachedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromEmailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromEmailDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string identifierKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string identifierValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool isAttached;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string attFilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string attFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool isHtml;
        
        public sendGridEmailwihtAttachedRequestBody() {
        }
        
        public sendGridEmailwihtAttachedRequestBody(string toEmail, string ccEmail, string bccEmail, string fromEmailAddress, string fromEmailDisplayName, string subject, string msgBody, string category, string identifierKey, string identifierValue, bool isAttached, string attFilePath, string attFileName, bool isHtml) {
            this.toEmail = toEmail;
            this.ccEmail = ccEmail;
            this.bccEmail = bccEmail;
            this.fromEmailAddress = fromEmailAddress;
            this.fromEmailDisplayName = fromEmailDisplayName;
            this.subject = subject;
            this.msgBody = msgBody;
            this.category = category;
            this.identifierKey = identifierKey;
            this.identifierValue = identifierValue;
            this.isAttached = isAttached;
            this.attFilePath = attFilePath;
            this.attFileName = attFileName;
            this.isHtml = isHtml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendGridEmailwihtAttachedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendGridEmailwihtAttachedResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendGridEmailwihtAttachedResponseBody Body;
        
        public sendGridEmailwihtAttachedResponse() {
        }
        
        public sendGridEmailwihtAttachedResponse(AwsEmailAPI.sendGridEmailwihtAttachedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendGridEmailwihtAttachedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendGridEmailwihtAttachedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMsg;
        
        public sendGridEmailwihtAttachedResponseBody() {
        }
        
        public sendGridEmailwihtAttachedResponseBody(bool sendGridEmailwihtAttachedResult, string errMsg) {
            this.sendGridEmailwihtAttachedResult = sendGridEmailwihtAttachedResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailByteArrayAttachedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailByteArrayAttached", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendEmailByteArrayAttachedRequestBody Body;
        
        public sendEmailByteArrayAttachedRequest() {
        }
        
        public sendEmailByteArrayAttachedRequest(AwsEmailAPI.sendEmailByteArrayAttachedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailByteArrayAttachedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromEmailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromEmailDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string identifierKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string identifierValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool isAttached;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] attFilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string attFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool isHtml;
        
        public sendEmailByteArrayAttachedRequestBody() {
        }
        
        public sendEmailByteArrayAttachedRequestBody(string toEmail, string ccEmail, string bccEmail, string fromEmailAddress, string fromEmailDisplayName, string subject, string msgBody, string category, string identifierKey, string identifierValue, bool isAttached, byte[] attFilePath, string attFileName, bool isHtml) {
            this.toEmail = toEmail;
            this.ccEmail = ccEmail;
            this.bccEmail = bccEmail;
            this.fromEmailAddress = fromEmailAddress;
            this.fromEmailDisplayName = fromEmailDisplayName;
            this.subject = subject;
            this.msgBody = msgBody;
            this.category = category;
            this.identifierKey = identifierKey;
            this.identifierValue = identifierValue;
            this.isAttached = isAttached;
            this.attFilePath = attFilePath;
            this.attFileName = attFileName;
            this.isHtml = isHtml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailByteArrayAttachedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailByteArrayAttachedResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendEmailByteArrayAttachedResponseBody Body;
        
        public sendEmailByteArrayAttachedResponse() {
        }
        
        public sendEmailByteArrayAttachedResponse(AwsEmailAPI.sendEmailByteArrayAttachedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailByteArrayAttachedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendEmailByteArrayAttachedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMsg;
        
        public sendEmailByteArrayAttachedResponseBody() {
        }
        
        public sendEmailByteArrayAttachedResponseBody(bool sendEmailByteArrayAttachedResult, string errMsg) {
            this.sendEmailByteArrayAttachedResult = sendEmailByteArrayAttachedResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailEmbededImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailEmbededImage", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendEmailEmbededImageRequestBody Body;
        
        public sendEmailEmbededImageRequest() {
        }
        
        public sendEmailEmbededImageRequest(AwsEmailAPI.sendEmailEmbededImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailEmbededImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromEmailAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromEmailDisplayName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string identifierKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string identifierValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] image1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string contentID1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public byte[] image2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string contentID2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public byte[] image3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string contentID3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public byte[] image4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string contentID4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public bool isHtml;
        
        public sendEmailEmbededImageRequestBody() {
        }
        
        public sendEmailEmbededImageRequestBody(
                    string toEmail, 
                    string ccEmail, 
                    string bccEmail, 
                    string fromEmailAddress, 
                    string fromEmailDisplayName, 
                    string subject, 
                    string msgBody, 
                    string category, 
                    string identifierKey, 
                    string identifierValue, 
                    byte[] image1, 
                    string contentID1, 
                    byte[] image2, 
                    string contentID2, 
                    byte[] image3, 
                    string contentID3, 
                    byte[] image4, 
                    string contentID4, 
                    bool isHtml) {
            this.toEmail = toEmail;
            this.ccEmail = ccEmail;
            this.bccEmail = bccEmail;
            this.fromEmailAddress = fromEmailAddress;
            this.fromEmailDisplayName = fromEmailDisplayName;
            this.subject = subject;
            this.msgBody = msgBody;
            this.category = category;
            this.identifierKey = identifierKey;
            this.identifierValue = identifierValue;
            this.image1 = image1;
            this.contentID1 = contentID1;
            this.image2 = image2;
            this.contentID2 = contentID2;
            this.image3 = image3;
            this.contentID3 = contentID3;
            this.image4 = image4;
            this.contentID4 = contentID4;
            this.isHtml = isHtml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailEmbededImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailEmbededImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public AwsEmailAPI.sendEmailEmbededImageResponseBody Body;
        
        public sendEmailEmbededImageResponse() {
        }
        
        public sendEmailEmbededImageResponse(AwsEmailAPI.sendEmailEmbededImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailEmbededImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool sendEmailEmbededImageResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMsg;
        
        public sendEmailEmbededImageResponseBody() {
        }
        
        public sendEmailEmbededImageResponseBody(bool sendEmailEmbededImageResult, string errMsg) {
            this.sendEmailEmbededImageResult = sendEmailEmbededImageResult;
            this.errMsg = errMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : AwsEmailAPI.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AwsEmailAPI.ServiceSoap>, AwsEmailAPI.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendMailResponse AwsEmailAPI.ServiceSoap.sendMail(AwsEmailAPI.sendMailRequest request) {
            return base.Channel.sendMail(request);
        }
        
        public bool sendMail(string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendMailRequest inValue = new AwsEmailAPI.sendMailRequest();
            inValue.Body = new AwsEmailAPI.sendMailRequestBody();
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            AwsEmailAPI.sendMailResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendMail(inValue);
            return retVal.Body.sendMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendMailResponse> AwsEmailAPI.ServiceSoap.sendMailAsync(AwsEmailAPI.sendMailRequest request) {
            return base.Channel.sendMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendMailResponse> sendMailAsync(string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendMailRequest inValue = new AwsEmailAPI.sendMailRequest();
            inValue.Body = new AwsEmailAPI.sendMailRequestBody();
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendMailCDONTSResponse AwsEmailAPI.ServiceSoap.sendMailCDONTS(AwsEmailAPI.sendMailCDONTSRequest request) {
            return base.Channel.sendMailCDONTS(request);
        }
        
        public bool sendMailCDONTS(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendMailCDONTSRequest inValue = new AwsEmailAPI.sendMailCDONTSRequest();
            inValue.Body = new AwsEmailAPI.sendMailCDONTSRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            AwsEmailAPI.sendMailCDONTSResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendMailCDONTS(inValue);
            return retVal.Body.sendMailCDONTSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendMailCDONTSResponse> AwsEmailAPI.ServiceSoap.sendMailCDONTSAsync(AwsEmailAPI.sendMailCDONTSRequest request) {
            return base.Channel.sendMailCDONTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendMailCDONTSResponse> sendMailCDONTSAsync(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendMailCDONTSRequest inValue = new AwsEmailAPI.sendMailCDONTSRequest();
            inValue.Body = new AwsEmailAPI.sendMailCDONTSRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendMailCDONTSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendGridMailResponse AwsEmailAPI.ServiceSoap.sendGridMail(AwsEmailAPI.sendGridMailRequest request) {
            return base.Channel.sendGridMail(request);
        }
        
        public bool sendGridMail(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendGridMailRequest inValue = new AwsEmailAPI.sendGridMailRequest();
            inValue.Body = new AwsEmailAPI.sendGridMailRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            AwsEmailAPI.sendGridMailResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendGridMail(inValue);
            return retVal.Body.sendGridMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendGridMailResponse> AwsEmailAPI.ServiceSoap.sendGridMailAsync(AwsEmailAPI.sendGridMailRequest request) {
            return base.Channel.sendGridMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendGridMailResponse> sendGridMailAsync(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendGridMailRequest inValue = new AwsEmailAPI.sendGridMailRequest();
            inValue.Body = new AwsEmailAPI.sendGridMailRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendGridMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendGridMailWithCategoryResponse AwsEmailAPI.ServiceSoap.sendGridMailWithCategory(AwsEmailAPI.sendGridMailWithCategoryRequest request) {
            return base.Channel.sendGridMailWithCategory(request);
        }
        
        public bool sendGridMailWithCategory(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body, string strCategory) {
            AwsEmailAPI.sendGridMailWithCategoryRequest inValue = new AwsEmailAPI.sendGridMailWithCategoryRequest();
            inValue.Body = new AwsEmailAPI.sendGridMailWithCategoryRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.strCategory = strCategory;
            AwsEmailAPI.sendGridMailWithCategoryResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendGridMailWithCategory(inValue);
            return retVal.Body.sendGridMailWithCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendGridMailWithCategoryResponse> AwsEmailAPI.ServiceSoap.sendGridMailWithCategoryAsync(AwsEmailAPI.sendGridMailWithCategoryRequest request) {
            return base.Channel.sendGridMailWithCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendGridMailWithCategoryResponse> sendGridMailWithCategoryAsync(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body, string strCategory) {
            AwsEmailAPI.sendGridMailWithCategoryRequest inValue = new AwsEmailAPI.sendGridMailWithCategoryRequest();
            inValue.Body = new AwsEmailAPI.sendGridMailWithCategoryRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.strCategory = strCategory;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendGridMailWithCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendAWSMailResponse AwsEmailAPI.ServiceSoap.sendAWSMail(AwsEmailAPI.sendAWSMailRequest request) {
            return base.Channel.sendAWSMail(request);
        }
        
        public bool sendAWSMail(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendAWSMailRequest inValue = new AwsEmailAPI.sendAWSMailRequest();
            inValue.Body = new AwsEmailAPI.sendAWSMailRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            AwsEmailAPI.sendAWSMailResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendAWSMail(inValue);
            return retVal.Body.sendAWSMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendAWSMailResponse> AwsEmailAPI.ServiceSoap.sendAWSMailAsync(AwsEmailAPI.sendAWSMailRequest request) {
            return base.Channel.sendAWSMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendAWSMailResponse> sendAWSMailAsync(string fromEmail, string fromDisplayName, string to, string cc, string bcc, string subject, string body) {
            AwsEmailAPI.sendAWSMailRequest inValue = new AwsEmailAPI.sendAWSMailRequest();
            inValue.Body = new AwsEmailAPI.sendAWSMailRequestBody();
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.fromDisplayName = fromDisplayName;
            inValue.Body.to = to;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendAWSMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendGridEmailwihtAttachedResponse AwsEmailAPI.ServiceSoap.sendGridEmailwihtAttached(AwsEmailAPI.sendGridEmailwihtAttachedRequest request) {
            return base.Channel.sendGridEmailwihtAttached(request);
        }
        
        public bool sendGridEmailwihtAttached(string toEmail, string ccEmail, string bccEmail, string fromEmailAddress, string fromEmailDisplayName, string subject, string msgBody, string category, string identifierKey, string identifierValue, bool isAttached, string attFilePath, string attFileName, bool isHtml, out string errMsg) {
            AwsEmailAPI.sendGridEmailwihtAttachedRequest inValue = new AwsEmailAPI.sendGridEmailwihtAttachedRequest();
            inValue.Body = new AwsEmailAPI.sendGridEmailwihtAttachedRequestBody();
            inValue.Body.toEmail = toEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.fromEmailAddress = fromEmailAddress;
            inValue.Body.fromEmailDisplayName = fromEmailDisplayName;
            inValue.Body.subject = subject;
            inValue.Body.msgBody = msgBody;
            inValue.Body.category = category;
            inValue.Body.identifierKey = identifierKey;
            inValue.Body.identifierValue = identifierValue;
            inValue.Body.isAttached = isAttached;
            inValue.Body.attFilePath = attFilePath;
            inValue.Body.attFileName = attFileName;
            inValue.Body.isHtml = isHtml;
            AwsEmailAPI.sendGridEmailwihtAttachedResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendGridEmailwihtAttached(inValue);
            errMsg = retVal.Body.errMsg;
            return retVal.Body.sendGridEmailwihtAttachedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendGridEmailwihtAttachedResponse> AwsEmailAPI.ServiceSoap.sendGridEmailwihtAttachedAsync(AwsEmailAPI.sendGridEmailwihtAttachedRequest request) {
            return base.Channel.sendGridEmailwihtAttachedAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendGridEmailwihtAttachedResponse> sendGridEmailwihtAttachedAsync(string toEmail, string ccEmail, string bccEmail, string fromEmailAddress, string fromEmailDisplayName, string subject, string msgBody, string category, string identifierKey, string identifierValue, bool isAttached, string attFilePath, string attFileName, bool isHtml) {
            AwsEmailAPI.sendGridEmailwihtAttachedRequest inValue = new AwsEmailAPI.sendGridEmailwihtAttachedRequest();
            inValue.Body = new AwsEmailAPI.sendGridEmailwihtAttachedRequestBody();
            inValue.Body.toEmail = toEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.fromEmailAddress = fromEmailAddress;
            inValue.Body.fromEmailDisplayName = fromEmailDisplayName;
            inValue.Body.subject = subject;
            inValue.Body.msgBody = msgBody;
            inValue.Body.category = category;
            inValue.Body.identifierKey = identifierKey;
            inValue.Body.identifierValue = identifierValue;
            inValue.Body.isAttached = isAttached;
            inValue.Body.attFilePath = attFilePath;
            inValue.Body.attFileName = attFileName;
            inValue.Body.isHtml = isHtml;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendGridEmailwihtAttachedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendEmailByteArrayAttachedResponse AwsEmailAPI.ServiceSoap.sendEmailByteArrayAttached(AwsEmailAPI.sendEmailByteArrayAttachedRequest request) {
            return base.Channel.sendEmailByteArrayAttached(request);
        }
        
        public bool sendEmailByteArrayAttached(string toEmail, string ccEmail, string bccEmail, string fromEmailAddress, string fromEmailDisplayName, string subject, string msgBody, string category, string identifierKey, string identifierValue, bool isAttached, byte[] attFilePath, string attFileName, bool isHtml, out string errMsg) {
            AwsEmailAPI.sendEmailByteArrayAttachedRequest inValue = new AwsEmailAPI.sendEmailByteArrayAttachedRequest();
            inValue.Body = new AwsEmailAPI.sendEmailByteArrayAttachedRequestBody();
            inValue.Body.toEmail = toEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.fromEmailAddress = fromEmailAddress;
            inValue.Body.fromEmailDisplayName = fromEmailDisplayName;
            inValue.Body.subject = subject;
            inValue.Body.msgBody = msgBody;
            inValue.Body.category = category;
            inValue.Body.identifierKey = identifierKey;
            inValue.Body.identifierValue = identifierValue;
            inValue.Body.isAttached = isAttached;
            inValue.Body.attFilePath = attFilePath;
            inValue.Body.attFileName = attFileName;
            inValue.Body.isHtml = isHtml;
            AwsEmailAPI.sendEmailByteArrayAttachedResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendEmailByteArrayAttached(inValue);
            errMsg = retVal.Body.errMsg;
            return retVal.Body.sendEmailByteArrayAttachedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendEmailByteArrayAttachedResponse> AwsEmailAPI.ServiceSoap.sendEmailByteArrayAttachedAsync(AwsEmailAPI.sendEmailByteArrayAttachedRequest request) {
            return base.Channel.sendEmailByteArrayAttachedAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendEmailByteArrayAttachedResponse> sendEmailByteArrayAttachedAsync(string toEmail, string ccEmail, string bccEmail, string fromEmailAddress, string fromEmailDisplayName, string subject, string msgBody, string category, string identifierKey, string identifierValue, bool isAttached, byte[] attFilePath, string attFileName, bool isHtml) {
            AwsEmailAPI.sendEmailByteArrayAttachedRequest inValue = new AwsEmailAPI.sendEmailByteArrayAttachedRequest();
            inValue.Body = new AwsEmailAPI.sendEmailByteArrayAttachedRequestBody();
            inValue.Body.toEmail = toEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.fromEmailAddress = fromEmailAddress;
            inValue.Body.fromEmailDisplayName = fromEmailDisplayName;
            inValue.Body.subject = subject;
            inValue.Body.msgBody = msgBody;
            inValue.Body.category = category;
            inValue.Body.identifierKey = identifierKey;
            inValue.Body.identifierValue = identifierValue;
            inValue.Body.isAttached = isAttached;
            inValue.Body.attFilePath = attFilePath;
            inValue.Body.attFileName = attFileName;
            inValue.Body.isHtml = isHtml;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendEmailByteArrayAttachedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AwsEmailAPI.sendEmailEmbededImageResponse AwsEmailAPI.ServiceSoap.sendEmailEmbededImage(AwsEmailAPI.sendEmailEmbededImageRequest request) {
            return base.Channel.sendEmailEmbededImage(request);
        }
        
        public bool sendEmailEmbededImage(
                    string toEmail, 
                    string ccEmail, 
                    string bccEmail, 
                    string fromEmailAddress, 
                    string fromEmailDisplayName, 
                    string subject, 
                    string msgBody, 
                    string category, 
                    string identifierKey, 
                    string identifierValue, 
                    byte[] image1, 
                    string contentID1, 
                    byte[] image2, 
                    string contentID2, 
                    byte[] image3, 
                    string contentID3, 
                    byte[] image4, 
                    string contentID4, 
                    bool isHtml, 
                    out string errMsg) {
            AwsEmailAPI.sendEmailEmbededImageRequest inValue = new AwsEmailAPI.sendEmailEmbededImageRequest();
            inValue.Body = new AwsEmailAPI.sendEmailEmbededImageRequestBody();
            inValue.Body.toEmail = toEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.fromEmailAddress = fromEmailAddress;
            inValue.Body.fromEmailDisplayName = fromEmailDisplayName;
            inValue.Body.subject = subject;
            inValue.Body.msgBody = msgBody;
            inValue.Body.category = category;
            inValue.Body.identifierKey = identifierKey;
            inValue.Body.identifierValue = identifierValue;
            inValue.Body.image1 = image1;
            inValue.Body.contentID1 = contentID1;
            inValue.Body.image2 = image2;
            inValue.Body.contentID2 = contentID2;
            inValue.Body.image3 = image3;
            inValue.Body.contentID3 = contentID3;
            inValue.Body.image4 = image4;
            inValue.Body.contentID4 = contentID4;
            inValue.Body.isHtml = isHtml;
            AwsEmailAPI.sendEmailEmbededImageResponse retVal = ((AwsEmailAPI.ServiceSoap)(this)).sendEmailEmbededImage(inValue);
            errMsg = retVal.Body.errMsg;
            return retVal.Body.sendEmailEmbededImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AwsEmailAPI.sendEmailEmbededImageResponse> AwsEmailAPI.ServiceSoap.sendEmailEmbededImageAsync(AwsEmailAPI.sendEmailEmbededImageRequest request) {
            return base.Channel.sendEmailEmbededImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<AwsEmailAPI.sendEmailEmbededImageResponse> sendEmailEmbededImageAsync(
                    string toEmail, 
                    string ccEmail, 
                    string bccEmail, 
                    string fromEmailAddress, 
                    string fromEmailDisplayName, 
                    string subject, 
                    string msgBody, 
                    string category, 
                    string identifierKey, 
                    string identifierValue, 
                    byte[] image1, 
                    string contentID1, 
                    byte[] image2, 
                    string contentID2, 
                    byte[] image3, 
                    string contentID3, 
                    byte[] image4, 
                    string contentID4, 
                    bool isHtml) {
            AwsEmailAPI.sendEmailEmbededImageRequest inValue = new AwsEmailAPI.sendEmailEmbededImageRequest();
            inValue.Body = new AwsEmailAPI.sendEmailEmbededImageRequestBody();
            inValue.Body.toEmail = toEmail;
            inValue.Body.ccEmail = ccEmail;
            inValue.Body.bccEmail = bccEmail;
            inValue.Body.fromEmailAddress = fromEmailAddress;
            inValue.Body.fromEmailDisplayName = fromEmailDisplayName;
            inValue.Body.subject = subject;
            inValue.Body.msgBody = msgBody;
            inValue.Body.category = category;
            inValue.Body.identifierKey = identifierKey;
            inValue.Body.identifierValue = identifierValue;
            inValue.Body.image1 = image1;
            inValue.Body.contentID1 = contentID1;
            inValue.Body.image2 = image2;
            inValue.Body.contentID2 = contentID2;
            inValue.Body.image3 = image3;
            inValue.Body.contentID3 = contentID3;
            inValue.Body.image4 = image4;
            inValue.Body.contentID4 = contentID4;
            inValue.Body.isHtml = isHtml;
            return ((AwsEmailAPI.ServiceSoap)(this)).sendEmailEmbededImageAsync(inValue);
        }
    }
}
