//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESBPINWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PINRESULT", Namespace="http://schemas.datacontract.org/2004/07/EBA.Web.PinService")]
    [System.SerializableAttribute()]
    public partial class PINRESULT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionStatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber {
            get {
                return this.SerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumberField, value) != true)) {
                    this.SerialNumberField = value;
                    this.RaisePropertyChanged("SerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionStatus {
            get {
                return this.TransactionStatusField;
            }
            set {
                if ((this.TransactionStatusField.Equals(value) != true)) {
                    this.TransactionStatusField = value;
                    this.RaisePropertyChanged("TransactionStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ESBPINWCF.IPinService")]
    public interface IPinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinService/GetTelcoPIN", ReplyAction="http://tempuri.org/IPinService/GetTelcoPINResponse")]
        ESBPINWCF.PINRESULT GetTelcoPIN(string Token, string Channel, string BillerCode, string NetworkType, string PriceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPinService/GetGiftCardPIN", ReplyAction="http://tempuri.org/IPinService/GetGiftCardPINResponse")]
        ESBPINWCF.PINRESULT GetGiftCardPIN(string Token, string Channel, string BillerCode, string PriceType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPinServiceChannel : ESBPINWCF.IPinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PinServiceClient : System.ServiceModel.ClientBase<ESBPINWCF.IPinService>, ESBPINWCF.IPinService {
        
        public PinServiceClient() {
        }
        
        public PinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ESBPINWCF.PINRESULT GetTelcoPIN(string Token, string Channel, string BillerCode, string NetworkType, string PriceType) {
            return base.Channel.GetTelcoPIN(Token, Channel, BillerCode, NetworkType, PriceType);
        }
        
        public ESBPINWCF.PINRESULT GetGiftCardPIN(string Token, string Channel, string BillerCode, string PriceType) {
            return base.Channel.GetGiftCardPIN(Token, Channel, BillerCode, PriceType);
        }
    }
}
