//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YpayService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterBillResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MeterBillResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterChargeOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Legno {
            get {
                return this.LegnoField;
            }
            set {
                if ((object.ReferenceEquals(this.LegnoField, value) != true)) {
                    this.LegnoField = value;
                    this.RaisePropertyChanged("Legno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TownshipCode {
            get {
                return this.TownshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipCodeField, value) != true)) {
                    this.TownshipCodeField = value;
                    this.RaisePropertyChanged("TownshipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BillCharge {
            get {
                return this.BillChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillChargeField, value) != true)) {
                    this.BillChargeField = value;
                    this.RaisePropertyChanged("BillCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MeterChargeOnly {
            get {
                return this.MeterChargeOnlyField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterChargeOnlyField, value) != true)) {
                    this.MeterChargeOnlyField = value;
                    this.RaisePropertyChanged("MeterChargeOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string MeterServiceCharge {
            get {
                return this.MeterServiceChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterServiceChargeField, value) != true)) {
                    this.MeterServiceChargeField = value;
                    this.RaisePropertyChanged("MeterServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Hosp {
            get {
                return this.HospField;
            }
            set {
                if ((object.ReferenceEquals(this.HospField, value) != true)) {
                    this.HospField = value;
                    this.RaisePropertyChanged("Hosp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ServiceCharge {
            get {
                return this.ServiceChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceChargeField, value) != true)) {
                    this.ServiceChargeField = value;
                    this.RaisePropertyChanged("ServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string LastDate {
            get {
                return this.LastDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LastDateField, value) != true)) {
                    this.LastDateField = value;
                    this.RaisePropertyChanged("LastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string BankAccountNo {
            get {
                return this.BankAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNoField, value) != true)) {
                    this.BankAccountNoField = value;
                    this.RaisePropertyChanged("BankAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ResponseDescription {
            get {
                return this.ResponseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDescriptionField, value) != true)) {
                    this.ResponseDescriptionField = value;
                    this.RaisePropertyChanged("ResponseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterBillRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MeterBillRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Legno {
            get {
                return this.LegnoField;
            }
            set {
                if ((object.ReferenceEquals(this.LegnoField, value) != true)) {
                    this.LegnoField = value;
                    this.RaisePropertyChanged("Legno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TownshipCode {
            get {
                return this.TownshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipCodeField, value) != true)) {
                    this.TownshipCodeField = value;
                    this.RaisePropertyChanged("TownshipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterBillResponseATM", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MeterBillResponseATM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterChargeOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Legno {
            get {
                return this.LegnoField;
            }
            set {
                if ((object.ReferenceEquals(this.LegnoField, value) != true)) {
                    this.LegnoField = value;
                    this.RaisePropertyChanged("Legno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TownshipCode {
            get {
                return this.TownshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipCodeField, value) != true)) {
                    this.TownshipCodeField = value;
                    this.RaisePropertyChanged("TownshipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BillCharge {
            get {
                return this.BillChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillChargeField, value) != true)) {
                    this.BillChargeField = value;
                    this.RaisePropertyChanged("BillCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MeterChargeOnly {
            get {
                return this.MeterChargeOnlyField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterChargeOnlyField, value) != true)) {
                    this.MeterChargeOnlyField = value;
                    this.RaisePropertyChanged("MeterChargeOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string MeterServiceCharge {
            get {
                return this.MeterServiceChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterServiceChargeField, value) != true)) {
                    this.MeterServiceChargeField = value;
                    this.RaisePropertyChanged("MeterServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Hosp {
            get {
                return this.HospField;
            }
            set {
                if ((object.ReferenceEquals(this.HospField, value) != true)) {
                    this.HospField = value;
                    this.RaisePropertyChanged("Hosp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ServiceCharge {
            get {
                return this.ServiceChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceChargeField, value) != true)) {
                    this.ServiceChargeField = value;
                    this.RaisePropertyChanged("ServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string LastDate {
            get {
                return this.LastDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LastDateField, value) != true)) {
                    this.LastDateField = value;
                    this.RaisePropertyChanged("LastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ResponseDescription {
            get {
                return this.ResponseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDescriptionField, value) != true)) {
                    this.ResponseDescriptionField = value;
                    this.RaisePropertyChanged("ResponseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterBillRequestATM", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MeterBillRequestATM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Legno {
            get {
                return this.LegnoField;
            }
            set {
                if ((object.ReferenceEquals(this.LegnoField, value) != true)) {
                    this.LegnoField = value;
                    this.RaisePropertyChanged("Legno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CardHolderName {
            get {
                return this.CardHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardHolderNameField, value) != true)) {
                    this.CardHolderNameField = value;
                    this.RaisePropertyChanged("CardHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaidMeterBillResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaidMeterBillResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LEGNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterChargeOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HOSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovalCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LEGNO {
            get {
                return this.LEGNOField;
            }
            set {
                if ((object.ReferenceEquals(this.LEGNOField, value) != true)) {
                    this.LEGNOField = value;
                    this.RaisePropertyChanged("LEGNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TownshipCode {
            get {
                return this.TownshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipCodeField, value) != true)) {
                    this.TownshipCodeField = value;
                    this.RaisePropertyChanged("TownshipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string BillCharge {
            get {
                return this.BillChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillChargeField, value) != true)) {
                    this.BillChargeField = value;
                    this.RaisePropertyChanged("BillCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MeterChargeOnly {
            get {
                return this.MeterChargeOnlyField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterChargeOnlyField, value) != true)) {
                    this.MeterChargeOnlyField = value;
                    this.RaisePropertyChanged("MeterChargeOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string MeterServiceCharge {
            get {
                return this.MeterServiceChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterServiceChargeField, value) != true)) {
                    this.MeterServiceChargeField = value;
                    this.RaisePropertyChanged("MeterServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string HOSP {
            get {
                return this.HOSPField;
            }
            set {
                if ((object.ReferenceEquals(this.HOSPField, value) != true)) {
                    this.HOSPField = value;
                    this.RaisePropertyChanged("HOSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ServiceCharge {
            get {
                return this.ServiceChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceChargeField, value) != true)) {
                    this.ServiceChargeField = value;
                    this.RaisePropertyChanged("ServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string BankAccountNo {
            get {
                return this.BankAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountNoField, value) != true)) {
                    this.BankAccountNoField = value;
                    this.RaisePropertyChanged("BankAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ResponseDescription {
            get {
                return this.ResponseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDescriptionField, value) != true)) {
                    this.ResponseDescriptionField = value;
                    this.RaisePropertyChanged("ResponseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ApprovalCode {
            get {
                return this.ApprovalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalCodeField, value) != true)) {
                    this.ApprovalCodeField = value;
                    this.RaisePropertyChanged("ApprovalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaidMeterBillRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaidMeterBillRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillChargeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Legno {
            get {
                return this.LegnoField;
            }
            set {
                if ((object.ReferenceEquals(this.LegnoField, value) != true)) {
                    this.LegnoField = value;
                    this.RaisePropertyChanged("Legno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TownshipCode {
            get {
                return this.TownshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipCodeField, value) != true)) {
                    this.TownshipCodeField = value;
                    this.RaisePropertyChanged("TownshipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BillCharge {
            get {
                return this.BillChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillChargeField, value) != true)) {
                    this.BillChargeField = value;
                    this.RaisePropertyChanged("BillCharge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaidMeterBillRequestATM", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaidMeterBillRequestATM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BankIDField, value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MeterNo {
            get {
                return this.MeterNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterNoField, value) != true)) {
                    this.MeterNoField = value;
                    this.RaisePropertyChanged("MeterNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Legno {
            get {
                return this.LegnoField;
            }
            set {
                if ((object.ReferenceEquals(this.LegnoField, value) != true)) {
                    this.LegnoField = value;
                    this.RaisePropertyChanged("Legno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BillDateField, value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BillCharge {
            get {
                return this.BillChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillChargeField, value) != true)) {
                    this.BillChargeField = value;
                    this.RaisePropertyChanged("BillCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CardHolderName {
            get {
                return this.CardHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardHolderNameField, value) != true)) {
                    this.CardHolderNameField = value;
                    this.RaisePropertyChanged("CardHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YpayService.MeterBillServiceToBankSoap")]
    public interface MeterBillServiceToBankSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (MeterRequest) of message MeterRequest does not match the default value (GetMeterBill)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MeterRequest", ReplyAction="*")]
        YpayService.MeterRequest1 GetMeterBill(YpayService.MeterRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (MeterRequestObj) of message MeterRequestObj does not match the default value (GetMeterBill1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MeterRequestObj", ReplyAction="*")]
        YpayService.MeterRequestObj1 GetMeterBill1(YpayService.MeterRequestObj request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRequestATM) of message GetRequestATM does not match the default value (GetMeterBillATM)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestATM", ReplyAction="*")]
        YpayService.GetRequestATM1 GetMeterBillATM(YpayService.GetRequestATM request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRequestATMObj) of message GetRequestATMObj does not match the default value (GetMeterBillATM1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestATMObj", ReplyAction="*")]
        YpayService.GetRequestATMObj1 GetMeterBillATM1(YpayService.GetRequestATMObj request);
        
        // CODEGEN: Generating message contract since the wrapper name (RequestPaid) of message RequestPaid does not match the default value (PaidMeterBill)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestPaid", ReplyAction="*")]
        YpayService.RequestPaid1 PaidMeterBill(YpayService.RequestPaid request);
        
        // CODEGEN: Generating message contract since the wrapper name (RequestPaidObj) of message RequestPaidObj does not match the default value (PaidMeterBill1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestPaidObj", ReplyAction="*")]
        YpayService.RequestPaidObj1 PaidMeterBill1(YpayService.RequestPaidObj request);
        
        // CODEGEN: Generating message contract since the wrapper name (PaidATM) of message PaidATM does not match the default value (PaidMeterBillATM)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaidATM", ReplyAction="*")]
        YpayService.PaidATM1 PaidMeterBillATM(YpayService.PaidATM request);
        
        // CODEGEN: Generating message contract since the wrapper name (PaidATMObj) of message PaidATMObj does not match the default value (PaidMeterBillATM1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaidATMObj", ReplyAction="*")]
        YpayService.PaidATMObj1 PaidMeterBillATM1(YpayService.PaidATMObj request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MeterRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MeterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string metaNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string legno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string billDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string bankName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string bankID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string townshipCode;
        
        public MeterRequest() {
        }
        
        public MeterRequest(string metaNo, string legno, string billDate, string securityCode, string bankName, string bankID, string townshipCode) {
            this.metaNo = metaNo;
            this.legno = legno;
            this.billDate = billDate;
            this.securityCode = securityCode;
            this.bankName = bankName;
            this.bankID = bankID;
            this.townshipCode = townshipCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MeterRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MeterRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.MeterBillResponse MeterRequestResult;
        
        public MeterRequest1() {
        }
        
        public MeterRequest1(YpayService.MeterBillResponse MeterRequestResult) {
            this.MeterRequestResult = MeterRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MeterRequestObj", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MeterRequestObj {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.MeterBillRequest meterBillRequest;
        
        public MeterRequestObj() {
        }
        
        public MeterRequestObj(YpayService.MeterBillRequest meterBillRequest) {
            this.meterBillRequest = meterBillRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MeterRequestObjResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MeterRequestObj1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.MeterBillResponse MeterRequestObjResult;
        
        public MeterRequestObj1() {
        }
        
        public MeterRequestObj1(YpayService.MeterBillResponse MeterRequestObjResult) {
            this.MeterRequestObjResult = MeterRequestObjResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestATM", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestATM {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string metaNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string legno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string cardNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string cardHolderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string transactionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string billDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string bankName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string bankID;
        
        public GetRequestATM() {
        }
        
        public GetRequestATM(string metaNo, string legno, string cardNo, string cardHolderName, string transactionCode, string billDate, string securityCode, string bankName, string bankID) {
            this.metaNo = metaNo;
            this.legno = legno;
            this.cardNo = cardNo;
            this.cardHolderName = cardHolderName;
            this.transactionCode = transactionCode;
            this.billDate = billDate;
            this.securityCode = securityCode;
            this.bankName = bankName;
            this.bankID = bankID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestATMResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestATM1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.MeterBillResponseATM GetRequestATMResult;
        
        public GetRequestATM1() {
        }
        
        public GetRequestATM1(YpayService.MeterBillResponseATM GetRequestATMResult) {
            this.GetRequestATMResult = GetRequestATMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestATMObj", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestATMObj {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.MeterBillRequestATM meterBillRequest;
        
        public GetRequestATMObj() {
        }
        
        public GetRequestATMObj(YpayService.MeterBillRequestATM meterBillRequest) {
            this.meterBillRequest = meterBillRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestATMObjResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestATMObj1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.MeterBillResponseATM GetRequestATMObjResult;
        
        public GetRequestATMObj1() {
        }
        
        public GetRequestATMObj1(YpayService.MeterBillResponseATM GetRequestATMObjResult) {
            this.GetRequestATMObjResult = GetRequestATMObjResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestPaid", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestPaid {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string metaNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string billDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string bankName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string bankID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string townshipCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string legno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string billCharge;
        
        public RequestPaid() {
        }
        
        public RequestPaid(string metaNo, string billDate, string securityCode, string bankName, string bankID, string townshipCode, string legno, string billCharge) {
            this.metaNo = metaNo;
            this.billDate = billDate;
            this.securityCode = securityCode;
            this.bankName = bankName;
            this.bankID = bankID;
            this.townshipCode = townshipCode;
            this.legno = legno;
            this.billCharge = billCharge;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestPaidResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestPaid1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.PaidMeterBillResponse RequestPaidResult;
        
        public RequestPaid1() {
        }
        
        public RequestPaid1(YpayService.PaidMeterBillResponse RequestPaidResult) {
            this.RequestPaidResult = RequestPaidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestPaidObj", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestPaidObj {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.PaidMeterBillRequest paidRequest;
        
        public RequestPaidObj() {
        }
        
        public RequestPaidObj(YpayService.PaidMeterBillRequest paidRequest) {
            this.paidRequest = paidRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestPaidObjResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestPaidObj1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.PaidMeterBillResponse RequestPaidObjResult;
        
        public RequestPaidObj1() {
        }
        
        public RequestPaidObj1(YpayService.PaidMeterBillResponse RequestPaidObjResult) {
            this.RequestPaidObjResult = RequestPaidObjResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaidATM", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaidATM {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string metaNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string billDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string cardNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string cardHolderName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string transactionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string bankName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string bankID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string legno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string billCharge;
        
        public PaidATM() {
        }
        
        public PaidATM(string metaNo, string billDate, string securityCode, string cardNo, string cardHolderName, string transactionCode, string bankName, string bankID, string legno, string billCharge) {
            this.metaNo = metaNo;
            this.billDate = billDate;
            this.securityCode = securityCode;
            this.cardNo = cardNo;
            this.cardHolderName = cardHolderName;
            this.transactionCode = transactionCode;
            this.bankName = bankName;
            this.bankID = bankID;
            this.legno = legno;
            this.billCharge = billCharge;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaidATMResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaidATM1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.PaidMeterBillResponse PaidATMResult;
        
        public PaidATM1() {
        }
        
        public PaidATM1(YpayService.PaidMeterBillResponse PaidATMResult) {
            this.PaidATMResult = PaidATMResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaidATMObj", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaidATMObj {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.PaidMeterBillRequestATM paidRequest;
        
        public PaidATMObj() {
        }
        
        public PaidATMObj(YpayService.PaidMeterBillRequestATM paidRequest) {
            this.paidRequest = paidRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaidATMObjResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaidATMObj1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public YpayService.PaidMeterBillResponse PaidATMObjResult;
        
        public PaidATMObj1() {
        }
        
        public PaidATMObj1(YpayService.PaidMeterBillResponse PaidATMObjResult) {
            this.PaidATMObjResult = PaidATMObjResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MeterBillServiceToBankSoapChannel : YpayService.MeterBillServiceToBankSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeterBillServiceToBankSoapClient : System.ServiceModel.ClientBase<YpayService.MeterBillServiceToBankSoap>, YpayService.MeterBillServiceToBankSoap {
        
        public MeterBillServiceToBankSoapClient() {
        }
        
        public MeterBillServiceToBankSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeterBillServiceToBankSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeterBillServiceToBankSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeterBillServiceToBankSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.MeterRequest1 YpayService.MeterBillServiceToBankSoap.GetMeterBill(YpayService.MeterRequest request) {
            return base.Channel.GetMeterBill(request);
        }
        
        public YpayService.MeterBillResponse GetMeterBill(string metaNo, string legno, string billDate, string securityCode, string bankName, string bankID, string townshipCode) {
            YpayService.MeterRequest inValue = new YpayService.MeterRequest();
            inValue.metaNo = metaNo;
            inValue.legno = legno;
            inValue.billDate = billDate;
            inValue.securityCode = securityCode;
            inValue.bankName = bankName;
            inValue.bankID = bankID;
            inValue.townshipCode = townshipCode;
            YpayService.MeterRequest1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).GetMeterBill(inValue);
            return retVal.MeterRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.MeterRequestObj1 YpayService.MeterBillServiceToBankSoap.GetMeterBill1(YpayService.MeterRequestObj request) {
            return base.Channel.GetMeterBill1(request);
        }
        
        public YpayService.MeterBillResponse GetMeterBill1(YpayService.MeterBillRequest meterBillRequest) {
            YpayService.MeterRequestObj inValue = new YpayService.MeterRequestObj();
            inValue.meterBillRequest = meterBillRequest;
            YpayService.MeterRequestObj1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).GetMeterBill1(inValue);
            return retVal.MeterRequestObjResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.GetRequestATM1 YpayService.MeterBillServiceToBankSoap.GetMeterBillATM(YpayService.GetRequestATM request) {
            return base.Channel.GetMeterBillATM(request);
        }
        
        public YpayService.MeterBillResponseATM GetMeterBillATM(string metaNo, string legno, string cardNo, string cardHolderName, string transactionCode, string billDate, string securityCode, string bankName, string bankID) {
            YpayService.GetRequestATM inValue = new YpayService.GetRequestATM();
            inValue.metaNo = metaNo;
            inValue.legno = legno;
            inValue.cardNo = cardNo;
            inValue.cardHolderName = cardHolderName;
            inValue.transactionCode = transactionCode;
            inValue.billDate = billDate;
            inValue.securityCode = securityCode;
            inValue.bankName = bankName;
            inValue.bankID = bankID;
            YpayService.GetRequestATM1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).GetMeterBillATM(inValue);
            return retVal.GetRequestATMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.GetRequestATMObj1 YpayService.MeterBillServiceToBankSoap.GetMeterBillATM1(YpayService.GetRequestATMObj request) {
            return base.Channel.GetMeterBillATM1(request);
        }
        
        public YpayService.MeterBillResponseATM GetMeterBillATM1(YpayService.MeterBillRequestATM meterBillRequest) {
            YpayService.GetRequestATMObj inValue = new YpayService.GetRequestATMObj();
            inValue.meterBillRequest = meterBillRequest;
            YpayService.GetRequestATMObj1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).GetMeterBillATM1(inValue);
            return retVal.GetRequestATMObjResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.RequestPaid1 YpayService.MeterBillServiceToBankSoap.PaidMeterBill(YpayService.RequestPaid request) {
            return base.Channel.PaidMeterBill(request);
        }
        
        public YpayService.PaidMeterBillResponse PaidMeterBill(string metaNo, string billDate, string securityCode, string bankName, string bankID, string townshipCode, string legno, string billCharge) {
            YpayService.RequestPaid inValue = new YpayService.RequestPaid();
            inValue.metaNo = metaNo;
            inValue.billDate = billDate;
            inValue.securityCode = securityCode;
            inValue.bankName = bankName;
            inValue.bankID = bankID;
            inValue.townshipCode = townshipCode;
            inValue.legno = legno;
            inValue.billCharge = billCharge;
            YpayService.RequestPaid1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).PaidMeterBill(inValue);
            return retVal.RequestPaidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.RequestPaidObj1 YpayService.MeterBillServiceToBankSoap.PaidMeterBill1(YpayService.RequestPaidObj request) {
            return base.Channel.PaidMeterBill1(request);
        }
        
        public YpayService.PaidMeterBillResponse PaidMeterBill1(YpayService.PaidMeterBillRequest paidRequest) {
            YpayService.RequestPaidObj inValue = new YpayService.RequestPaidObj();
            inValue.paidRequest = paidRequest;
            YpayService.RequestPaidObj1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).PaidMeterBill1(inValue);
            return retVal.RequestPaidObjResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.PaidATM1 YpayService.MeterBillServiceToBankSoap.PaidMeterBillATM(YpayService.PaidATM request) {
            return base.Channel.PaidMeterBillATM(request);
        }
        
        public YpayService.PaidMeterBillResponse PaidMeterBillATM(string metaNo, string billDate, string securityCode, string cardNo, string cardHolderName, string transactionCode, string bankName, string bankID, string legno, string billCharge) {
            YpayService.PaidATM inValue = new YpayService.PaidATM();
            inValue.metaNo = metaNo;
            inValue.billDate = billDate;
            inValue.securityCode = securityCode;
            inValue.cardNo = cardNo;
            inValue.cardHolderName = cardHolderName;
            inValue.transactionCode = transactionCode;
            inValue.bankName = bankName;
            inValue.bankID = bankID;
            inValue.legno = legno;
            inValue.billCharge = billCharge;
            YpayService.PaidATM1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).PaidMeterBillATM(inValue);
            return retVal.PaidATMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YpayService.PaidATMObj1 YpayService.MeterBillServiceToBankSoap.PaidMeterBillATM1(YpayService.PaidATMObj request) {
            return base.Channel.PaidMeterBillATM1(request);
        }
        
        public YpayService.PaidMeterBillResponse PaidMeterBillATM1(YpayService.PaidMeterBillRequestATM paidRequest) {
            YpayService.PaidATMObj inValue = new YpayService.PaidATMObj();
            inValue.paidRequest = paidRequest;
            YpayService.PaidATMObj1 retVal = ((YpayService.MeterBillServiceToBankSoap)(this)).PaidMeterBillATM1(inValue);
            return retVal.PaidATMObjResult;
        }
    }
}
