//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payhereMPTWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="payhereMPTWCF.IPINService")]
    public interface IPINService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/getPIN", ReplyAction="http://tempuri.org/IPINService/getPINResponse")]
        bool getPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/getPINMPT", ReplyAction="http://tempuri.org/IPINService/getPINMPTResponse")]
        bool getPINMPT(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/getVAKOKPIN", ReplyAction="http://tempuri.org/IPINService/getVAKOKPINResponse")]
        bool getVAKOKPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/getiTunesPIN", ReplyAction="http://tempuri.org/IPINService/getiTunesPINResponse")]
        bool getiTunesPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/ConfirmiTunesPIN", ReplyAction="http://tempuri.org/IPINService/ConfirmiTunesPINResponse")]
        bool ConfirmiTunesPIN(out string errMsg, out string fxAmount, double cardPrice, string cardType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/getPINOoredoo", ReplyAction="http://tempuri.org/IPINService/getPINOoredooResponse")]
        bool getPINOoredoo(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPINServiceChannel : payhereMPTWCF.IPINService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PINServiceClient : System.ServiceModel.ClientBase<payhereMPTWCF.IPINService>, payhereMPTWCF.IPINService {
        
        public PINServiceClient() {
        }
        
        public PINServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PINServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PINServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PINServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool getPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice) {
            return base.Channel.getPIN(out errMsg, out PIN, out expiryDate, out serialNumber, cardPrice);
        }
        
        public bool getPINMPT(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType) {
            return base.Channel.getPINMPT(out errMsg, out PIN, out expiryDate, out serialNumber, cardPrice, cardType);
        }
        
        public bool getVAKOKPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType) {
            return base.Channel.getVAKOKPIN(out errMsg, out PIN, out expiryDate, out serialNumber, cardPrice, cardType);
        }
        
        public bool getiTunesPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType) {
            return base.Channel.getiTunesPIN(out errMsg, out PIN, out expiryDate, out serialNumber, cardPrice, cardType);
        }
        
        public bool ConfirmiTunesPIN(out string errMsg, out string fxAmount, double cardPrice, string cardType) {
            return base.Channel.ConfirmiTunesPIN(out errMsg, out fxAmount, cardPrice, cardType);
        }
        
        public bool getPINOoredoo(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice) {
            return base.Channel.getPINOoredoo(out errMsg, out PIN, out expiryDate, out serialNumber, cardPrice);
        }
    }
}
