//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pushNotiWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="pushNotiWCF.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAndroid", ReplyAction="http://tempuri.org/IService/PushToAndroidResponse")]
        pushNotiWCF.PushToAndroidResponse PushToAndroid(pushNotiWCF.PushToAndroidRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAndroid", ReplyAction="http://tempuri.org/IService/PushToAndroidResponse")]
        System.Threading.Tasks.Task<pushNotiWCF.PushToAndroidResponse> PushToAndroidAsync(pushNotiWCF.PushToAndroidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToApple", ReplyAction="http://tempuri.org/IService/PushToAppleResponse")]
        pushNotiWCF.PushToAppleResponse PushToApple(pushNotiWCF.PushToAppleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToApple", ReplyAction="http://tempuri.org/IService/PushToAppleResponse")]
        System.Threading.Tasks.Task<pushNotiWCF.PushToAppleResponse> PushToAppleAsync(pushNotiWCF.PushToAppleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAppleOTP", ReplyAction="http://tempuri.org/IService/PushToAppleOTPResponse")]
        pushNotiWCF.PushToAppleOTPResponse PushToAppleOTP(pushNotiWCF.PushToAppleOTPRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PushToAppleOTP", ReplyAction="http://tempuri.org/IService/PushToAppleOTPResponse")]
        System.Threading.Tasks.Task<pushNotiWCF.PushToAppleOTPResponse> PushToAppleOTPAsync(pushNotiWCF.PushToAppleOTPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAndroid", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAndroidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public PushToAndroidRequest() {
        }
        
        public PushToAndroidRequest(string token, string message) {
            this.token = token;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAndroidResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAndroidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PushToAndroidResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public PushToAndroidResponse() {
        }
        
        public PushToAndroidResponse(bool PushToAndroidResult, string error) {
            this.PushToAndroidResult = PushToAndroidResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToApple", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int Badgecount;
        
        public PushToAppleRequest() {
        }
        
        public PushToAppleRequest(string token, string message, int Badgecount) {
            this.token = token;
            this.message = message;
            this.Badgecount = Badgecount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAppleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PushToAppleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public PushToAppleResponse() {
        }
        
        public PushToAppleResponse(bool PushToAppleResult, string error) {
            this.PushToAppleResult = PushToAppleResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAppleOTP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleOTPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string OTP;
        
        public PushToAppleOTPRequest() {
        }
        
        public PushToAppleOTPRequest(string token, string message, string OTP) {
            this.token = token;
            this.message = message;
            this.OTP = OTP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PushToAppleOTPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PushToAppleOTPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PushToAppleOTPResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string error;
        
        public PushToAppleOTPResponse() {
        }
        
        public PushToAppleOTPResponse(bool PushToAppleOTPResult, string error) {
            this.PushToAppleOTPResult = PushToAppleOTPResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : pushNotiWCF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<pushNotiWCF.IService>, pushNotiWCF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pushNotiWCF.PushToAndroidResponse pushNotiWCF.IService.PushToAndroid(pushNotiWCF.PushToAndroidRequest request) {
            return base.Channel.PushToAndroid(request);
        }
        
        public bool PushToAndroid(string token, string message, out string error) {
            pushNotiWCF.PushToAndroidRequest inValue = new pushNotiWCF.PushToAndroidRequest();
            inValue.token = token;
            inValue.message = message;
            pushNotiWCF.PushToAndroidResponse retVal = ((pushNotiWCF.IService)(this)).PushToAndroid(inValue);
            error = retVal.error;
            return retVal.PushToAndroidResult;
        }
        
        public System.Threading.Tasks.Task<pushNotiWCF.PushToAndroidResponse> PushToAndroidAsync(pushNotiWCF.PushToAndroidRequest request) {
            return base.Channel.PushToAndroidAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pushNotiWCF.PushToAppleResponse pushNotiWCF.IService.PushToApple(pushNotiWCF.PushToAppleRequest request) {
            return base.Channel.PushToApple(request);
        }
        
        public bool PushToApple(string token, string message, int Badgecount, out string error) {
            pushNotiWCF.PushToAppleRequest inValue = new pushNotiWCF.PushToAppleRequest();
            inValue.token = token;
            inValue.message = message;
            inValue.Badgecount = Badgecount;
            pushNotiWCF.PushToAppleResponse retVal = ((pushNotiWCF.IService)(this)).PushToApple(inValue);
            error = retVal.error;
            return retVal.PushToAppleResult;
        }
        
        public System.Threading.Tasks.Task<pushNotiWCF.PushToAppleResponse> PushToAppleAsync(pushNotiWCF.PushToAppleRequest request) {
            return base.Channel.PushToAppleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pushNotiWCF.PushToAppleOTPResponse pushNotiWCF.IService.PushToAppleOTP(pushNotiWCF.PushToAppleOTPRequest request) {
            return base.Channel.PushToAppleOTP(request);
        }
        
        public bool PushToAppleOTP(string token, string message, string OTP, out string error) {
            pushNotiWCF.PushToAppleOTPRequest inValue = new pushNotiWCF.PushToAppleOTPRequest();
            inValue.token = token;
            inValue.message = message;
            inValue.OTP = OTP;
            pushNotiWCF.PushToAppleOTPResponse retVal = ((pushNotiWCF.IService)(this)).PushToAppleOTP(inValue);
            error = retVal.error;
            return retVal.PushToAppleOTPResult;
        }
        
        public System.Threading.Tasks.Task<pushNotiWCF.PushToAppleOTPResponse> PushToAppleOTPAsync(pushNotiWCF.PushToAppleOTPRequest request) {
            return base.Channel.PushToAppleOTPAsync(request);
        }
    }
}
