//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace telenorWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="telenorWCF.IPINService")]
    public interface IPINService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/getPIN", ReplyAction="http://tempuri.org/IPINService/getPINResponse")]
        bool getPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPINService/getPINMYANPAY", ReplyAction="http://tempuri.org/IPINService/getPINMYANPAYResponse")]
        bool getPINMYANPAY(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPINServiceChannel : telenorWCF.IPINService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PINServiceClient : System.ServiceModel.ClientBase<telenorWCF.IPINService>, telenorWCF.IPINService {
        
        public PINServiceClient() {
        }
        
        public PINServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PINServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PINServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PINServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool getPIN(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice) {
            return base.Channel.getPIN(out errMsg, out PIN, out expiryDate, out serialNumber, cardPrice);
        }
        
        public bool getPINMYANPAY(out string errMsg, out string PIN, out string expiryDate, out string serialNumber, double cardPrice, string cardType) {
            return base.Channel.getPINMYANPAY(out errMsg, out PIN, out expiryDate, out serialNumber, cardPrice, cardType);
        }
    }
}
