version: 0.2
phases:
build:
commands:
- msbuild ./BIS/website.publishproj /p:Configuration=Release /p:DeployIisAppPath="Default Web Site" /p:OutDir=\artifacts\ /t:Package -restore
artifacts:
files:
- \artifacts\_PublishedWebsites\Test.Web\**\*
- appspec.yml
- Scripts\**\*
exclude-paths:
- \artifacts\_PublishedWebsites\Test.Web\*.config
- \artifacts\_PublishedWebsites\Test.Web\*.cs
