name: .NET Framework CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild Environment
      uses: microsoft/setup-msbuild@v1.0.2

    - name: List directory contents (Debugging)
      run: ls -R
      shell: pwsh

    - name: Restore NuGet packages
      run: nuget Restore ./bis.sln
      shell: pwsh

    - name: Build the .NET Framework project
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU" ./bis.sln
      shell: pwsh

    # Optional: Add steps for testing if you have tests configured
    - name: Run tests
      run: |
        echo "Replace this command with your test runner command"
      shell: pwsh

    # Optional: Publish artifacts (e.g., compiled binaries or reports)
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Application
        path: ./BIS/Output/  # Update this path to where your binaries are placed after build

